### ISSUE TITLE
Fila de publicação: permissão de acesso

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#101]
@jeankirchner pode complementar este cartão? O comentário atual era:

"Verificar permissão de acesso à fila de publicação (apenas publicadores podem publicar)
Esse item está nesse nível, pois já há algumas funcionalidades básicas para ter controle de usuário, antes desse momento, como algumas coisas podem acontecer pelo github, não faz sentido controle de usuário nosso, sendo que o github vai ter apenas o usuário do editor"

**Comment by cv** [comment]
Duplicata de #76 e #77
