### ISSUE TITLE
Nome de serviço vs XML para serviços novos, renomeados, deletados

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#107]
Essa é uma história apenas para analisar os problemas abaixo:
- Novos serviços não tem nome, ao salvar, devemos validar, ou criar algum nome temporário (novo)?
- O usuário podem começar a edição de vários serviços novos, antes de terminar os anteriores?
- Vamos obrigá-lo antes de salvar, à no mínimo dar um nome para o serviço, por causa dessa relação com o nome do XML?
- Decidir o que deve ser feito com as situações de renomear um serviço, e deletar um serviço.

Criar os cartões para cada hipótese das soluções propostas.

**Comment by oliviagj** [comment]
virou #278
