### ISSUE TITLE
Testes de interface para cenários básicos de edição de serviços

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#118]
Testes para:
- [ ] adicionar novos solicitantes
- [ ] adicionar novas etapas
- [ ] adicionar novos custos
- [ ] adicionar novos documentos
- [ ] adicionar novos canais
- [ ] adicionar novos links
- [ ] preencher todos os campos e salvar

**Comment by sahrosa** [comment]
@kchnr acha que isso faz parte da entrega dessa semana? Onde o pessoal vai editar e testar o Editor?

**Comment by kchnr** [comment]
Vamos fechar esse cartão, a intenção era ter alguns testes automatizados na
interface, para garantir funcionalidades básicas, mas faria mais sentido,
criar cartões específicos para testes específicos. Este cartão está muito
"aberto".
