### ISSUE TITLE
Validação: limitação de caracteres no "Nome"

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#120]

**Comment by oliviagj** [comment]
Vamos limitar no mesmo tamanho que o maior nome de serviço atualmente registrado

**Comment by almeidafab** [comment]
faltou mostrar os caracteres restantes... a princípio ainda consigo inserir um nome bem grande.

**Comment by sahrosa** [comment]
Vamos limitar em 150 caracteres (maior serviço tem 148).

![image](https://cloud.githubusercontent.com/assets/2932644/8908950/42532f2a-3455-11e5-9261-26d4f9da67b7.png)

**Comment by cv** [comment]
Duplicata do #210
