### ISSUE TITLE
Hora da última atualização está incorreta

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#135]
Está mostrando 3 horas adiantadas ao horário de Brasília.

**Comment by cv** [comment]
O horário das máquinas na EC2 está configurado para UTC. Em desenvolvimento e produção, as máquinas estão configuradas para o horário de Brasília, e tudo deve funcionar.

**Comment by caduvieira** [comment]
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html
Pode ser que ajude

**Comment by cv** [comment]
Valeu @caduvieira! :clap: 

Resolvi usando o `timedatectl` e instalando e rodando o `ntpd` na máquina da EC2.

**Comment by sahrosa** [comment]
:metal:
