### ISSUE TITLE
Orientação sobre o que é um serviço

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/editor-de-servicos#139]
Épico da falta de consenso e pouca maturidade, no Governo Federal, da conversa sobre o que é um serviço.

**Comment by oliviagj** [comment]
Podemos começar por tirar do portal aquilo que não é serviço? @mformiga, @almeidafab

**Comment by sahrosa** [comment]
@oliviagj, criei o cartão #206 para a exclusão do que não é serviço

**Comment by sahrosa** [comment]
Sobre o conteúdo genérico, de orientar sobre o que é um serviço, podemos fazer algo neste repositório? Ou posso excluir e colocar um cartão no consultoria?

**Comment by oliviagj** [comment]
Acho que é aqui mesmo, na documentação, perto do Guia de Linguagem.

Meta de consultoria: envolver Asege e Segepe para cuidarem desta
documentação na continuidade do projeto.

**Comment by sahrosa** [comment]
Legal!

Vou incluir o conteúdo que tínhamos sobre o que é um serviço dentro da documentação! E vamos melhorando conforme a conversa com Asege e Segepe andam :)

**Comment by kchnr** [comment]
#207 vai cuidar disso.
