### ISSUE TITLE
Explicitar a finalidade do campo "O que é?"

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/editor-de-servicos#141]
Como em vários outros campos, os servidores do MDS não se apoiaram (ou não foi suficiente fazê-lo) na descrição do campo e no ex. colocado como placeholder.

Precisamos aprimorar a estratégia para guiar o servidor no preenchimento dos campos.

**Comment by oliviagj** [comment]
- Idéia para estimular a leitura: tirar o texto e colocar a interrogação
- Link para um guia de desenho de serviços (ASEGE? SEGEP?)

**Comment by sahrosa** [comment]
Para estimular a leitura e o melhor preenchimentos:
* Melhoramos o texto para "Descrição sobre o que é este serviço"
* Incluímos a tooltip (interrogação) com um breve texto sobre como o campo deverá ser preenchido.

![image](https://cloud.githubusercontent.com/assets/2932644/8932349/f6120604-3512-11e5-8996-dfeef3a6f294.png)

**Comment by cv** [comment]
A ser resolvido pelo #168
