### ISSUE TITLE
Texto da disponibilidade do serviço em meio eletrônico não está claro

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#142]
Algumas pessoas não entenderam o que queríamos dizer com "meio eletrônico" - alguns acharam que eletrônico = atendente cadastrar no computador.

![image](https://cloud.githubusercontent.com/assets/2932644/8735791/d6983654-2be9-11e5-8ef5-4697cd1e3ff1.png)

**Comment by sahrosa** [comment]
Oi @almeidafab e @mformiga. Estamos pensando aqui sobre este campo, se ele é realmente necessário. No início do editor, ele auxiliava na contextualização de outros campos. Mas agora, ele tem apenas um objetivo claro, que é nos ajudar a perceber em longo prazo as mudanças em um serviço: 
* Se ele era apenas presencial, e se tornou parcialmente eletrônico.
* Se o serviço era parcialmente eletrônico e se tornou totalmente...

Enfim, consegui ver quantos % de serviços estão em quais situações, e tal. 

Acham que faz sentido continuar pedindo essa informação?

**Comment by mformiga** [comment]
@sahrosa Acho que dá para obter estas informações a partir dos tipos dos canais cadastrados para cada etapa, não dá ?

**Comment by sahrosa** [comment]
Infelizmente não temos como inferir esses dados pelos canais, @mformiga :(

Acho que essa informação pode ser pouco importante no curto prazo mas no longo prazo pode ser uma fonte de dados bem significativa.

**Comment by sahrosa** [comment]
Olá pessoal! Ontem o @mformiga e eu conversamos sobre essa questão, e concordamos que faz mais sentido não termos esse campo. O que acontece é que poderemos obter a informação sobre o status do serviço (eletrônico, parcialmente eletrônico, ou não) através do histórico de edição dos canais de prestação.

Estou fechando este cartão!
