### ISSUE TITLE
Como indicar que um documento é opcional?

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/editor-de-servicos#145]
No caso do Bolsa Família, as servidoras indicaram que alguns documentos facilitam o processamento do pedido do benefício, mas não são obrigatórios pela regulamentação do programa. Elas ressaltaram também que em alguns municípios documentos não-obrigatórios são tratados irregularmente como obrigatórios pelos servidores municipais que operam localmente o Cadastro Único.

**Comment by sahrosa** [comment]
Acredito que usando os casos, seria fácil resolver esse cenário, pois poderia ter um caso para "Documentos opcionais". O que acha @oliviagj?

![image](https://cloud.githubusercontent.com/assets/2932644/8932176/bf553bb4-3511-11e5-9a0a-49183779299b.png)

**Comment by oliviagj** [comment]
Faz sentido, @sahrosa, acho que funcionará.
