### ISSUE TITLE
Repensar apresentação de exemplo de preenchimento 

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#146]
Os exemplos de preenchimento de campos estão confundindo os servidores durante a edição.

**Comment by sahrosa** [comment]
Para resolver este caso, criamos uma forma de tooltip de apresentar as intruções, e quando necessário, exemplo:

![image](https://cloud.githubusercontent.com/assets/2932644/8907669/ef925aba-344d-11e5-9810-ccad154ef667.png)

**Comment by cv** [comment]
Será resolvido pela #168
