### ISSUE TITLE
Salvar serviços automaticamente

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#148]
Acreditamos que salvar o serviço automaticamente será uma forma de facilitar o processo de criação de um serviço, além de evitar possíveis erros (que podem ocorrer caso a internet caia, o sistema tenha algum problema, etc)

**Comment by sahrosa** [comment]
Resolvemos da seguinte forma na interface:

![image](https://cloud.githubusercontent.com/assets/2932644/8908022/10d79f80-3450-11e5-8dc0-4719e6772df9.png)

**Comment by jeankirchner** [comment]
De quanto em quanto tempo vamos querer salvar? (30 segundos, 1 minuto, 5 minutos)?
Não vai mais existir botão salvar?

**Comment by sahrosa** [comment]
Se tivermos como salvar automaticamente, não teremos o botão 'salvar' pois isso irá confundir ainda mais o servidor. 

Sobre o tempo, podemos criar uma regra que não atrapalhe em performance, e testar e ir refinando. Acho que poderia ser algo como:
* Se o servidor estiver editando o serviço, salvamos a cada ação (escrever em um campo, selecionar uma opção, etc).
* Se o servidor não estiver editando, não precisamos salvar. 

Faz sentido algo assim @jeankirchner?

**Comment by sahrosa** [comment]
No Google docs é assim. Gosto dessa forma pois conseguimos mostrar quando foi a última edição:

![image](https://cloud.githubusercontent.com/assets/2932644/8934928/7e73e794-3520-11e5-8006-27c42fe2fa3a.png)

A regra poderia ser:
* Salvo automaticamente às 18:33
* Última edição foi salva às 18:33 de ontem
* Última edição foi salva às 18:33 de 26/07/2015

**Comment by sahrosa** [comment]
No Google docs é assim. Gosto dessa forma pois conseguimos mostrar quando foi a última edição:

![image](https://cloud.githubusercontent.com/assets/2932644/8934928/7e73e794-3520-11e5-8006-27c42fe2fa3a.png)

A regra poderia ser:
* Salvo automaticamente às 18:33
* Última edição foi salva às 18:33 de ontem
* Última edição foi salva às 18:33 de 26/07/2015

**Comment by cv** [comment]
Importante: a data e hora exibidas no texto "salvo automaticamente às…" deve vir do servidor (no header `Last-Modified`), e não do cliente. Não podemos confiar no horário do browser :(

**Comment by sahrosa** [comment]
Melhor então mostrar  "há 30 minutos" @cv ?

**Comment by cv** [comment]
A exibição da informação pode ser o quão humana quisermos, o importante é que a **fonte** dessa informação seja o header `Last-Modified`, vindo do servidor :)

**Comment by almeidafab** [comment]
O texto "Salvo por ..." fica legal.
