### ISSUE TITLE
Alertar para possíveis irregularidades

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/editor-de-servicos#149]
No experimento do MDS, surgiu a necessidade de oferecer aos cidadãos alertas sobre possíveis irregularidades de forma contextualizada. O exemplo dado foi o da solicitação irregular de documentos por parte dos operadores do Cadastro Único nos municípios.

Complementarmente, podemos pensar, talvez, em uma oferta mais ativa de canal de denúncia.

**Comment by sahrosa** [comment]
Podemos colocar um aviso genérico avisando sobre possíveis irregularidades?

**Comment by kchnr** [comment]
Esse tipo de situação, pode ocorrer apenas em serviços específicos, não é todo o caso que isso seria relevante. Assim o "Caso" poderia resolver, adicionando informações como canais  para denúncia por exemplo.

Também nessas situações, há muitas coisas específicas do serviço quer seria complicado tratar no portal ou no editor.

Podemos fechar?
