### ISSUE TITLE
Cadastro e autenticação de novos usuários

### ISSUE THREAD

**Issue by erickpintor** [servicosgovbr/editor-de-servicos#15]
Como parte do ticket #6, criamos a estrutura para efetuar login e logout de usuários.
Precisamos agora entender como o cadastro de novos usuários irão funcionar no sistema.

Iremos manter um cadastro próprio de usuários?
Podemos utilizar de algum cadastro já existente como LDAP, por exemplo?

Tarefas:
- [ ] Permitir o login de novos usuários no sistema
- [ ] Administrar papéis de usuários (super, administrador, publicador)

**Comment by cv** [comment]
Sobreposto pelo #77
