### ISSUE TITLE
Limite pequeno no campo "o que é?"

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#155]
- Acharam que o limite de 500 muito pequeno para descrever o serviço

**Comment by sahrosa** [comment]
Então, aqui fica uma dúvida... será que o limite é realmente pequeno? Será que as pessoas só ainda não estão acostumadas a escrever na nova estrutura que estamos propondo, e por cut/paste toda a informação que tinham antes, acham que era pouco espaço? 

O que acham @oliviagj @cv @kchnr? Queremos que eles sejam realmente sucintos... este texto por exemplo, tem 500 caracteres. Acham que devemos aumentar um pouco?

> O Programa Universidade para Todos (ProUni), criado em 2004, oferece bolsas de estudos em instituições particulares de educação superior a estudantes egressos do ensino médio da rede pública. Também são atendidos bolsistas integrais oriundos da rede particular. Para a bolsa integral, o candidato precisa comprovar renda bruta familiar, por pessoa, de até 1,5 salário mínimo. Para a bolsa parcial, de até três salários mínimos. Estão dispensados dos requisitos de renda professores efetivo exercício.

**Comment by oliviagj** [comment]
Eu acho que o limite tem que ser esse mesmo ou menor. Este texto do Prouni,
por exemplo, podia ter parado aqui:

O Programa Universidade para Todos (ProUni), criado em 2004, oferece bolsas
> de estudos em instituições particulares de educação superior a estudantes
> egressos do ensino médio da rede pública. Também são atendidos bolsistas
> integrais oriundos da rede particular.


As demais informações cabem nos campos estruturados para isso.

**Comment by sahrosa** [comment]
Concordo. Fechando este cartão!
