### ISSUE TITLE
Erros nos textos de canais de comunição dentro de etapas

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/editor-de-servicos#161]
Dentro das etapas, o texto "Canais de comunicação com este serviço:" está incorreto e deveria ser: "Canais de prestação desta etapa:"

**Comment by sahrosa** [comment]
@jeankirchner acho que faz mais sentido mudarmos este cartão pro repositório do Portal de Serviços, certo? Já que os erros são na visão do cidadão.

**Comment by sahrosa** [comment]
Sendo resolvido no cartão https://github.com/servicosgovbr/portal-de-servicos/issues/435
