### ISSUE TITLE
Adicionar documento, confundido com "Anexar"

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#172]
Confundiram adicionar documentos com eles terem que "anexar documentos"

**Comment by sahrosa** [comment]
Hmmm, podemos trocar o termo, mas será que isso é algo que aconteceu mais vezes? @oliviagj @cv @almeidafab @mformiga vocês viram isso acontecer mais vezes?

**Comment by cv** [comment]
Acho que isso se resolve com alguns segundos de uso, não devíamos nos preocupar em mudar a UI nesse caso.

**Comment by caduvieira** [comment]
Concordo com o @cv

**Comment by kchnr** [comment]
+1
