### ISSUE TITLE
Edição em markdown não é clara para os servidores

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#174]
Não conseguiram usar os links e só entenderam listas depois de utilizar um pouco.

**Comment by caduvieira** [comment]
Precisa ser algo mais fácil que MD? Agora entendo o cv quando diz que LaTeX não é 'para humanos'. Não existe nenhum editor visual simples que gere MD no final?

**Comment by sahrosa** [comment]
Este cartão está sendo resolvido com duas soluções: 
* Deixando os campos de preenchimento abertos, mas com acesso ao preview do serviço. Esse é o ponto mais importante: uma vez que é possível fazer e ver como está ficando, fica mais fácil editar da forma correta.
* Dicas de markdown, assim como o Github possui (Markdown supported). No entanto ainda não temos estas dicas em português, e precisaríamos realizar essa tradução (cartão #194).

**Comment by sahrosa** [comment]
Este cartão será resolvido com outro cartão, o #194
