### ISSUE TITLE
Limitar os tipos de entrada por finalidade do campo

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/editor-de-servicos#179]

**Comment by sahrosa** [comment]
@oliviagj pode clarificar melhor este cartão?

**Comment by oliviagj** [comment]
É o problema de validação, @sahrosa. Por exemplo: um campo de custo que aceita texto; um campo de URL que aceita um texto sem ".domínio"

**Comment by sahrosa** [comment]
Entendi, perfeito @oliviagj!

**Comment by sahrosa** [comment]
Relacionada com a #71
