### ISSUE TITLE
Taxas não são o único custo para o cidadão

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/editor-de-servicos#180]
Esta situação partiu de um caso do MDS (também pode ser necessidade de outros órgãos), onde existe a situação de que, por exemplo, o transporte até o local do atendimento pode ser considerado como custo pelo cidadão. 

* Uma possibilidade seria explicitar que quando o serviço é gratuito, não existem taxas a serem pagas.
* Outra possibilidade é explicitar que custos como transporte, etc, são responsabilidade do cidadão.

**Comment by sahrosa** [comment]
Podemos colocar um disclaimer genérico sobre as taxas com uma das duas opções acima. Que tal @oliviagj?

**Comment by cv** [comment]
Esse disclaimer pode ser adicionado como parte da descrição do serviço ou etapa. Fechando esse cartão por enquanto.
