### ISSUE TITLE
Sobreposição de entendimento entre Linha da vida e Áreas de Interesse

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/editor-de-servicos#182]
Testar só com a VCGE?

**Comment by oliviagj** [comment]
@mformiga @almeidafab Confirmando: vamos matar as linhas da vida e deixar só as áreas da VCGE

**Comment by oliviagj** [comment]
Precisamos fazer essa decisão refletir no Portal, com uma mudança importante no menu esquerda @cv @sahrosa @kchnr

**Comment by sahrosa** [comment]
Podemos retirar as linhas da vida também do Editor @oliviagj @mformiga @almeidafab ?

**Comment by cv** [comment]
Sim! :fireworks:

**Comment by cv** [comment]
Bloqueado até a gente ter uma decisão sobre VCGE, linhas da vida e o que a gente quer fazer das categorias - rolou uma sugestão de não ter mais o menu de navegação à esquerda, que acho que vale a pena estudar.

**Comment by almeidafab** [comment]
@cv @oliviagj @sahrosa @mformiga fizemos uma reunião hoje com a segep, Andrea e Silvia e fechamos essa questão. Realmente vamos retirar linha da vida e deixar o VCGE. Teve uma outra ideia sobre a retirada do menu da esquerda somente na página inicial para que possamos priorizar a busca. Todos também concordaram. Enfim, é isso.

**Comment by cv** [comment]
https://github.com/servicosgovbr/editor-de-servicos/issues/294#issuecomment-136690708
