### ISSUE TITLE
Campo de texto rico não utilizado

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/editor-de-servicos#184]
Observando o MJ:
    - simplesmente não usaram nenhum recurso de formatação (listas, link)
    - não estavam entendendo a caixa a direita (a que mostra renderizado) e estava confundindo eles

**Comment by cv** [comment]
Também vimos isso no exercício da assinatura do DOU. Proponho mudar a disposição dos campos para a mesma que temos aqui no GitHub:

<img width="739" alt="screen shot 2015-07-17 at 6 56 29 pm" src="https://cloud.githubusercontent.com/assets/5445/8757993/958840ba-2cb5-11e5-8d17-99268bc670e9.png">

**Comment by cv** [comment]
Duplicada da #174
