### ISSUE TITLE
Possibilidade de trocar serviço de órgão

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/editor-de-servicos#187]
- Serviços que não fazem mais parte do órgão e passaram a ser de outros órgãos, e gostariam de transferir facilmente

**Comment by cv** [comment]
Ué, não é só escolher o órgão novo na caixa de seleção? O que falta?

**Comment by sahrosa** [comment]
Mas se a seleção de órgão for automática, não será possível a edição. Será que vale a pena manter a seleção do órgão ao invés de automatizar?

**Comment by cv** [comment]
Manter a seleção, mas usar o órgão a qual o servidor pertence como padrão (caso ainda não tenha sido especificado no serviço).

**Comment by sahrosa** [comment]
Show @cv! Pra mim essa é a melhor opção :)
