### ISSUE TITLE
Feedback de validação agregado p/ área (menu lateral)

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#196]
Para auxiliar o servidor a compreender o que falta ser preenchido, criamos uma forma visual de demonstrar quanto já foi preenchido:

![image](https://cloud.githubusercontent.com/assets/2932644/8933880/560bafe4-351b-11e5-8407-32f0e4b436fd.png)

**Comment by jeankirchner** [comment]
"Preenchida corretamente", acredito que isso vai depender um pouco de validações certo? Talvez já vale a pena criar um cartão de validação para cada campo, especificando claramente quando um preenchimento está valido?

Eu separaria um pouco dos opcionais vs obrigatórios, porque isso ainda vai ser um pouco debatido e pode ser trabalhado separadamente.

**Comment by sahrosa** [comment]
Com certeza @jeankirchner! Temos um cartão de validação, o #71. Mas acho que ele precisa ser beeeem quebrado. Eu tinha começado a fazer isso com a #120, #121 e #122. Mas precisamos quebrar bem mais.

**Comment by oliviagj** [comment]
e a gente mantém esse cara aqui ou ele vai virar outros?

**Comment by sahrosa** [comment]
Sim! Ele depende dos cartões de validação, mas este cartão continua existindo!

**Comment by oliviagj** [comment]
Não por agora, @sahrosa. Vamos matar cartões longínquos e se a necessidade
ressurgir, será um novo cartão, no novo contexto

**Comment by sahrosa** [comment]
Fechando este cartão por estar fora do escopo ok @mformiga @almeidafab @gustavo-freitas? :)

**Comment by gustavo-freitas** [comment]
Conforme conversa com Fabrício, entendemos que:
- A possibilidade de 'Despublicar', 'Remover Alterações' e 'Excluir' adiciona ruído ao entendimento das funcionalidades do Editor pelo servidor. Nesse sentido, botão excluir na lista dos serviços, ficará oculto por agora. Confirmar comportamento com @mformiga.
- O botão 'Despublicar' não ficará ao lado do ícone de 'Remover Alterações', no topo da página do Editor. Decidimos mover esse botão para logo abaixo da lista de etapas, no lado esquerdo da edição do serviço. Além disso, seria ideal termos um link para a versão atual do serviço, indo diretamente para o Portal. Caso serviço não esteja publicado, botão deve estar desabilitado. Talvez, um texto alternativo mencionando que serviço não está no ar possa ser exibido também. @sahrosa faz sentido?

**Comment by sahrosa** [comment]
Faz todo o sentido @gustavo-freitas. Quer que eu faça um mockup de como pode ficar isso?!

**Comment by gustavo-freitas** [comment]
Por favor @sahrosa :)
