### ISSUE TITLE
Excluir serviços antigos que não são serviços

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#206]
Olá @mformiga e @almeidafab. Como conversamos na semana passada, um bom começo para termos melhores serviços no Portal poderia ser excluir os itens que não são serviços, como por exemplo o [Acesso ao Sistema SISCOSERV](http://www.servicos.gov.br/servico/acesso-ao-sistema-siscoserv?pk_campaign=busca).

Vocês podem continuar essa conversa? Se precisarem de algo, só avisar!

**Comment by almeidafab** [comment]
@sahrosa vamos conversar com a ASEGE e SEGEP sobre o assunto. Depois repassamos o feedback

**Comment by sahrosa** [comment]
Show @almeidafab! :)

**Comment by almeidafab** [comment]
@sahrosa após reunião com a SEGEP e Andrea hoje, ficou decidido que essa questão não será resolvida nesse momento em virtude do tempo. Retomaremos essa questão no ano que vem. Sugiro fechar esse cartão.
