### ISSUE TITLE
Remover duplicação de "Previdência Social" em Áreas de Interesse

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/editor-de-servicos#235]

**Comment by cv** [comment]
Essa não é a diferença entre "Proteção Social" e "Previdência Social", @almeidafab?

**Comment by almeidafab** [comment]
acho que não @cv, aparece "Previdência Social" nas duas colunas, da esquerda e da direita.

**Comment by cv** [comment]
D'oh! Tinha dois: "Previdência Social" e "Previdência social". O primeiro é usado por serviços na v1, então removi o segundo.
