### ISSUE TITLE
Gratuidade como checkbox

### ISSUE THREAD

**Issue by cv** [servicosgovbr/editor-de-servicos#240]
Para o campo “Gratuidade deste serviço” basta colocar uma opção com checkbox para o caso de não gratuidade do serviço.

**Comment by cv** [comment]
@sahrosa comentou, por email:

> se dermos apenas o checkbox, não saberemos se o servidor deixou desmarcado intencionalmente... e isso pode se tornar um problema.

**Comment by cv** [comment]
@mformiga comentou, por e-mail:

> Legal Samantha, concordo com o número 3, só peço para não deixar o texto tão repetitivo. Faz a pergunta e obriga o usuário a escolher sim ou não, o que acha?

**Comment by mformiga** [comment]
Obrigado @cv pelo que vi do e-mail da @sahrosa achei que talvez não tivesse colocado esse.
