### ISSUE TITLE
Expandir textareas automaticamente

### ISSUE THREAD

**Issue by cv** [servicosgovbr/editor-de-servicos#242]
Colocar todos os campos do tamanho de uma linha inicialmente, exceto no campo descrição do serviço. À medida que o texto for ultrapassar o limite horizontal, o campo vai aumentando na vertical. Em algumas situações, o usuário estava inserindo todos os itens de uma vez sem selecionar a opção para adicionar.

**Comment by cv** [comment]
500 caracteres dá mais ou menos 6 linhas em uma textarea no nosso tamanho de fonte.

**Comment by sahrosa** [comment]
Fechando esse cartão pois está fora do escopo, ok @almeidafab @mformiga @gustavo-freitas ?
