### ISSUE TITLE
Formulário muito extenso

### ISSUE THREAD

**Issue by cv** [servicosgovbr/editor-de-servicos#244]
O formulário está ficando ainda muito extenso e com muitos campos repetitivos. Pedimos para que nos campos em que há lista, o campo para preenchimento apareça uma única vez e que os itens já inseridos apareçam em outro formato.

**Comment by glauberramos** [comment]
relacionado com #269

**Comment by sahrosa** [comment]
Estamos fechando esse cartão porque é duplicado do #269 como o @glauberramos falou. Vamos repriorizar o outro conforme este aqui.
