### ISSUE TITLE
Estruturar campos de endereço em canais presenciais

### ISSUE THREAD

**Issue by cv** [servicosgovbr/editor-de-servicos#247]
No tipo presencial houve sugestão de pegar o cep e os dados pré-cadastrados nos correios. Também houve sugestão de colocar separar os campos obrigatórios do endereço presencial para não correr o risco de endereços incompletos.

**Comment by oliviagj** [comment]
Mudei o título porque abrimos mão da consulta à base dos correios

**Comment by sahrosa** [comment]
O problema que vejo em limitar em um campo exato de endereço é que se não houver um endereço específico e for apenas "agências da caixa", deixamos sem a possibilidade de incluir um link para localizador de agências, etc...

**Comment by cv** [comment]
Conversamos bastante sobre como isso pode ser feito na semana passada, e não acho que tenhamos chegado a um consenso. @almeidafab @mformiga, opiniões?

**Comment by almeidafab** [comment]
@cv conversando com o Maurício achamos melhor fechar esse cartão pois estávamos pensando em estruturar esse campo mas há poucos casos de serviços que usam o endereço dessa forma. Do jeito que está hoje nos atende.

**Comment by cv** [comment]
Excelente!
