### ISSUE TITLE
Melhorias na busca de serviços

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#253]
- [x] Não está funcionando pesquisar por letras maíusculas (FTGS por exemplo) - case sensitive
- [x] letras especiais não funcionam (exemplo ç)
- [x] pesquisar com 'espaço' no final da palavra não retorna resultados 
- [ ] na primeira pesquisa demora mais de 10 segundos para carregar qualquer coisa
- [ ] não há feedback para aguardar busca ser realizada

**Comment by cv** [comment]
A primeira pesquisa demora mesmo - temos que colher metadados de todos os serviços existentes e colocá-los no cache. Com sorte, isso só acontece na primeira vez que o editor for acessado após um deployment, então não acho que precisamos nos preocupar.

Sobre o feedback da busca, acho que podemos fazê-lo como parte da #274, então vou fechar esse cartão.
