### ISSUE TITLE
Permitir cadastro incompleto

### ISSUE THREAD

**Issue by cv** [servicosgovbr/editor-de-servicos#26]
Do #18:

> O formulário pede diversos textos que o usuário pode não ter ao iniciar o processo. Neste caso, é arriscado que ele comece a fazer a descrição numa planilha ou num documento do Word, por exemplo, tendo depois o retrabalho de transcrevê-lo no Guia. Assim, sugiro que seja permitido o cadastro de serviços incompletos mas que, neste caso, o usuário seja alertado de que o serviço só será ativado no site quando as demais informações estiverem preenchidas.

**Comment by jeankirchner** [comment]
Como estamos pensando em mais ações/formas de indicar o status do documento, eu pensei em algum tipo de barra de ferramentas que acompanha a visão do usuário durante a rolagem, lateralmente ou no topo, e com algumas coisas à mais:
- Algum ícone de status, indicando se é rascunho, ou um documento publicado
- Botão para descartar alterações
- Botão para salvar como rascunho
- Botão para publicar serviço no guia de serviços

O que acham? Ações demais?

Futuramente, com essa abordagem de barra de ferramentas também é possível:
- Botão para validar campos, e identificar possíveis erros
- Botão para preview no guia de serviços como as informações do serviço sendo cadastrado ficaria

**Comment by cv** [comment]
Achei muito complicado, ainda mais com o fluxo de publicação tão confuso (ou tão simples, se a gente for pro mesmo fluxo de um pull request aqui no Github)...

Vamos achar uma lousa e rabiscar umas opções com a @sahrosa?

**Comment by sahrosa** [comment]
Vamos sim @cv! Acho que isso tem tudo a ver com a #30!

**Comment by cv** [comment]
Fechando este cartão, que ficou irrelevante depois das mudanças no fluxo do #8
