### ISSUE TITLE
Campos não são salvos

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#263]
nunca é salvo:
- [ ] nome do serviço nunca é salvo

dependendo do serviço:
- [ ] segmento da sociedade
- [ ] areas de interesse
- [ ] eventos da linha da vida

**Comment by cv** [comment]
Trocar o nome do serviço pode ser meio complicado de mostrar pro usuário... a não ser que a gente implemente a funcionalidade de renomear cartas como algo "separado" na UI, o que eu não acho ser uma boa ideia...

Enfim, o problema é que o editor está salvando corretamente, mas quando o nome troca a gente está salvando uma _outra carta_, em um _novo branch_, e mantendo a carta antiga como estava até então.

**Comment by sahrosa** [comment]
Entendi @cv! O problema que eu vejo é que a gente pede pra pessoa colocar a sigla num campo separado, justamente pra organizar melhor, mas a sigla geralmente já está no nome. E se não conseguir editar, fica com a sigla repetida em diferentes padrões. 

Uma opção seria ajustarmos manualmente os serviços que são legado e que possuem sigla no nome (início ou fim, entre parênteses, sem parênteses). É fáctivel?

Aí ajustando legado, a gente não precisa se preocupar com edição do nome daqui pra frente :)

**Comment by cv** [comment]
É chato, mas é factível :)

Teríamos que revisar os 591 serviços disponíveis hoje, e colocar a sigla no
campo separado, caso exista.

2015-08-21 14:42 GMT-03:00 Samantha Rosa <notifications@github.com>:

**Comment by sahrosa** [comment]
Pois é, acho que nem todos tem essa situação. Talvez nos custe uma horinha, mas compensa na padronização. Vamos pensando!

**Comment by cv** [comment]
Não consegui reproduzir o bug, @sahrosa - se for válido ainda, reabre o cartão por favor?
