### ISSUE TITLE
Caso a sessão caia, o usuário não pode continuar editando o serviço

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#264]
É preciso avisar que ele está desconectado e precisa se logar novamente.

**Comment by cv** [comment]
Melhor: usuário pode continuar editando, mas quando sessão cai ou ele perde a conexão, um aviso é exibido e ele pode resolver o problema sem perder as alterações que fez. Quando o indicador de status ficar verde de novo, ele pode tentar salvar novamente:

<img width="322" alt="screen shot 2015-08-14 at 6 03 51 pm" src="https://cloud.githubusercontent.com/assets/5445/9287405/4d4dc7da-42e9-11e5-8ae5-4010ef8ed132.png">
