### ISSUE TITLE
Feedback para quando o usuário for desconectado da internet

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#266]
Exemplo 1: http://github.hubspot.com/offline/docs/welcome/

Exemplo 2: https://cloud.githubusercontent.com/assets/2932644/8939067/c69799ea-3538-11e5-9b14-bf5138d79efa.png

Exemplo 3: https://cloud.githubusercontent.com/assets/2932644/8933778/fe528a16-351a-11e5-8d9f-cb1e7d36e284.png

**Comment by cv** [comment]
O indicador foi criado como parte do #195.
