### ISSUE TITLE
Feedback para quando sessão expirar

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#267]
Caso onde isso aconteceu: sessão expirou e nada foi avisado ao usuário, que perdeu tudo o que fez. Continuou editando e novamente perdeu tudo que havia sido feito.

**Comment by cv** [comment]
Adicionei um semáforo de status simples ali na barra:

<img width="322" alt="screen shot 2015-08-14 at 6 03 51 pm" src="https://cloud.githubusercontent.com/assets/5445/9284114/729f2310-42af-11e5-93b0-82bc3b585bd6.png">

<img width="313" alt="screen shot 2015-08-14 at 6 04 05 pm" src="https://cloud.githubusercontent.com/assets/5445/9284111/6ca5c9fa-42af-11e5-8e9b-41b073a46757.png">

<img width="341" alt="screen shot 2015-08-14 at 6 04 19 pm" src="https://cloud.githubusercontent.com/assets/5445/9284116/75ea491e-42af-11e5-94da-c034bfd58948.png">
