### ISSUE TITLE
Definição de nomes populares e palavras-chave com tagging do select2

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#269]
![image](https://cloud.githubusercontent.com/assets/2932644/9258207/84a465f0-41d0-11e5-9a3b-9fb1eaa798a9.png)

https://select2.github.io/examples.html

**Comment by almeidafab** [comment]
seria interessante a mesma ideia também para canais, documentação e etapas. Não usando tagging mas outra forma q permita uma visualização mais enxuta dos campos já cadastrados. @mformiga @sahrosa

**Comment by cv** [comment]
Certeza que esse cartão é prioridade 0, pessoal?

**Comment by kchnr** [comment]
Acredito que isso seja um cartão "2", o que acham?

**Comment by sahrosa** [comment]
Concordo. Não tenho uma lembrança clara do porque mudamos para 0.

**Comment by sahrosa** [comment]
Fechando este cartão por estar fora do escopo ok @mformiga @almeidafab @gustavo-freitas? :)
