### ISSUE TITLE
Incluir busca por legislação no lexml

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#270]
- [ ] incluir placeholder de url lexml
- [ ] incluir lupa com link para site lexml

**Comment by cv** [comment]
De acordo com o https://github.com/servicosgovbr/editor-de-servicos/issues/171#issuecomment-137621428, não vamos nos preocupar com isso agora. Quando aprendermos qual a necessidade do órgão, abriremos outro cartão.
