### ISSUE TITLE
Preencher palavras-chave com nomes populares

### ISSUE THREAD

**Issue by cv** [servicosgovbr/editor-de-servicos#272]
Ao adicionar um nome popular, automaticamente adicioná-lo às palavras-chave

**Comment by sahrosa** [comment]
Não entendi porque faríamos isso @cv? Se for assim, não faz sentido realmente unificar as duas coisas em um campo só?

**Comment by cv** [comment]
Acho que não vale a pena unificar, pois podemos ter palavras-chave que a gente sabe que cidadãos usam, mas não queremos mostrar na página do serviço ("bolsa-esmola", por exemplo).

Então, nomes populares são exibidos e influenciam pouco na busca, mas palavras chave não são exibidas (e influenciam bastante na busca).

**Comment by sahrosa** [comment]
Entendi! Mas onde nós exibimos os nomes populares? 

Hoje ainda não exibimos em nenhum lugar. Mas vejo valor em mostrar "Carteira Nacional de Habilitação (CHN) - Também conhecido como: carteira de motorista, carta de motorista". Se acharem que faz sentido, podemos criar um cartão pra isso.

**Comment by cv** [comment]
Acho que vamos ter todas estas conversas na hora de implementar a página do
serviço v3, também conhecida como
https://github.com/servicosgovbr/portal-de-servicos/issues/443 :)

2015-08-21 16:13 GMT-03:00 Samantha Rosa <notifications@github.com>:

**Comment by sahrosa** [comment]
Ok!
