### ISSUE TITLE
MAPEAMENTO DE DADOS - Campo Taxa

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/editor-de-servicos#273]
Analisando o documento de entrega do produto VI.1 – MAPEAMENTO DE DADOS, no tópico "Campos Convertidos", existem 2 serviços que possuiem taxa no legado ("Autorização de Trabalho a Estrangeiros" e "Passaporte") e não estão aparecendo na v3.

**Comment by almeidafab** [comment]
a taxa do passaporte foi atualizada para R$ 257,25.

**Comment by cv** [comment]
Como só existem 2 serviços nos dados legados com taxas definidas, acho que fica mais fácil consertar as informações manualmente do que descobrir a origem do problema, já que ele tem muito pouco impacto. Vou adicionar mais dois pull requests para trazer a informação de volta.

**Comment by cv** [comment]
https://github.com/servicosgovbr/cartas-de-servico/pull/19 e 
https://github.com/servicosgovbr/cartas-de-servico/pull/20
