### ISSUE TITLE
Janela "pop-up" para login quando sessão é expirada

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#281]
Hoje a janela abre em uma nova aba, e quando o usuário é conectado, é levado para a página da lista de serviços,  o que pode confundi-lo a procurar o serviço e começar novamente, podendo assim perder o que estava sendo feito na página original que ficou em outra aba.

**Comment by sahrosa** [comment]
Continuação da #279

**Comment by cv** [comment]
Não dá pra fazer um popup assim funcionar bem com soluções de Single Sign-on como o Gerid ou OpenID Connect, infelizmente. 




Melhor manter o link como está. :(



- cv
