### ISSUE TITLE
menu esquerdo da documentação com bug

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/editor-de-servicos#283]
Ao clicar em qualquer link do menu esquerdo (http://servicosgovbr.github.io/portal-de-servicos/) ele oculta várias outras opções.

**Comment by caduvieira** [comment]
Aqui não deu problema. Qual navegador / versão você está usando?

Em 25 de agosto de 2015 11:31, Fabrício Almeida <notifications@github.com>
escreveu:

**Comment by almeidafab** [comment]
@caduvieira vi que no chrome funciona, mas no firefox (versão 40) ta bugado. Toda vez que clico em qualquer item, o menu fica igual à imagem:

![captura de tela de 2015-08-25 14 30 09](https://cloud.githubusercontent.com/assets/9214263/9474259/e1484240-4b35-11e5-836a-79653188b1e4.png)

**Comment by caduvieira** [comment]
FF 40.0.2 aqui no Windows 8 tudo ok.

**Comment by cv** [comment]
Esse pode ser um problema no CSS do Gitbook. Vou abrir um bug lá e fechar aqui.
