### ISSUE TITLE
Definição dos principais fluxos de serviços

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#29]
Compreender todos os cenários de preenchimento de informações do Editor está mais complexo do que esperado (se é um serviço digital = mandamos o cidadão pra um lugar digital, se é presencial = mandamos pra um lugar digitial ou agendamento ou telefone, etc). Para simplificar, iremos definir os principais fluxos para a criação de conteúdo de serviços.

**Comment by cv** [comment]
Este cartão pode ser fechado, @sahrosa?
