### ISSUE TITLE
Listar os principais canais primeiro

### ISSUE THREAD

**Issue by cv** [servicosgovbr/editor-de-servicos#291]
na combo dos canais, listar os principais primeiro conforme conversado previamente;

**Comment by sahrosa** [comment]
Qual a motivação deste cartão @almeidafab? 

Como esta é uma lista de tamanho médio, a ordem alfabética auxilia na encontrabilidade do itens. Colocar em uma ordem arbitrária pode tornar a experiência ruim.

**Comment by almeidafab** [comment]
concordo @sahrosa o que acha @mformiga?

**Comment by mformiga** [comment]
@sahrosa @almeidafab sem problemas

**Comment by sahrosa** [comment]
Show!
