### ISSUE TITLE
VCGE em formato de árvore

### ISSUE THREAD

**Issue by cv** [servicosgovbr/editor-de-servicos#294]

**Comment by cv** [comment]
@mformiga @almeidafab batemos o martelo no VCGE 1 ou 2?

**Comment by cv** [comment]
A discussão sobre o VCGE está nos seguintes cartões:

* https://github.com/servicosgovbr/editor-de-servicos/issues/182#issuecomment-134619993 
* https://github.com/servicosgovbr/cartas-de-servico/issues/21

**Comment by cv** [comment]
O VCGE 1.0 provê um arquivo compatível com o jsTree: http://vocab.e.gov.br/2011/03/vcge-treeview.json que pode ser usado facilmente no Editor.

**Comment by almeidafab** [comment]
@cv em reunião com o DGE resolvemos adotar a versão 2 porém sem a opção "Outros" no segundo nível, ok?

**Comment by cv** [comment]
OK - nesse caso qualquer mapeamento no de-para fornecido pelo VCGE 2 que vá para as categorias 'Outros' fica no nível superior, então.

**Comment by mformiga** [comment]
@cv exato

**Comment by rslyra** [comment]
Bom dia. Roberto Lyra - responsável pela manutenção do VCGE.
O VCGE é uma recomendação, bem como sua forma de uso. Tivemos uma votação para retirar o OUTROS, onde eu votei pela retirada. Perdi, o OUTROS fica, pelo menos por enquanto. mas cada um faça o uso que quiser. 
Arquivos: estamos fechando essa semana a versão 2.1. tenho um mês para fazer todos os arquivos, inclusive o treeview. Se existe hoje, será feito uma nova versão, mas incluirá o OUTROS.
É bom saber que está em uso. 
Qualquer necessidade avisem.

**Comment by rslyra** [comment]
Apenas para ficar claro: recomendamos e esperamos que todos sigam a recomendação, ou proponham muda-la. Mas quem decidir não seguir a recomendação (parcial ou integral) tem liberdade para isso e não será um conflito. Mas proponham mudanças, propostas são benvindas. (propostas no forum do VCGE, aberto a todos).

**Comment by rslyra** [comment]
Bom dia. Roberto Lyra - responsável pela manutenção do VCGE.
O VCGE é uma recomendação, bem como sua forma de uso. Tivemos uma votação para retirar o OUTROS, onde eu votei pela retirada. Perdi, o OUTROS fica, pelo menos por enquanto. mas cada um faça o uso que quiser. 
Arquivos: esta,mos fechando essa semana a versão 2.1. tenho um mês para fazer todos os arquivos, inclusive o treeview. Se existe hoje, será feito uma nova versão, mas incluirá o OUTROS.
É bom saber que está em uso. 
Qualquer necessidade avisem.

**Comment by cv** [comment]
Muito obrigado pelos esclarecimentos, @rslyra! Foram bastante úteis :)

**Comment by mformiga** [comment]
@cv apenas reforçando que no editor devemos mostrar a árvore do vcge de forma hierárquica.

**Comment by rslyra** [comment]
Não temos uma recomendação sobre isso, então, e nossa parte, ok.


Em sex, 4 de set de 2015 às 10:52, mformiga <notifications@github.com>
escreveu:

**Comment by caduvieira** [comment]
Relacionado com #316

**Comment by augusto-herrmann** [comment]
Uma navegação em árvore pela taxonomia faz sentido do ponto de vista de UX? Será que não vai deixar o usuário confuso ou perdido? Sugiro fazer testes de UX, se possível. Comparar com um simples texto autocompletante.

**Comment by gustavo-freitas** [comment]
@oliviagj @mformiga @kchnr isso ainda é uma pendência? Considerando que o produto VI - Plano de Migrações de Dados já foi entregue podemos fechar esse cartão?
