### ISSUE TITLE
Alteração da descrição do serviço "Balanço Hídrico Climático""

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/editor-de-servicos#307]
Retirei esse texto do site do INMET. Sugiro a seguinte alteração:

- Descrição do serviço: "O balanço hídrico é uma maneira de monitorar o armazenamento de água no solo computando o volume de água que entra e que sai."

- Descrição da etapa: "Esse procedimento segue a metodologia proposta por THORNTHWAITE & MATHER (1955). A capacidade máxima de água disponível no solo foi fixada em 100 mm e a evapotranspiração potencial (ET0) foi estimada pelo método de THORNTHWAITE (1948). Os valores de temperatura e precipitação correspndem às médias históricas para os períodos de 1931-1960 e 1961-1990 (normais climatológicas), na localidade de interesse."

- Colocar também o acento no título "Hídrico".
- Atualizar o link para http://www.inmet.gov.br/portal/index.php?r=agrometeorologia/balancoHidricoClimatico

**Comment by cv** [comment]
Você pode fazer essas atualizações, @almeidafab? Ou melhor esperarmos por um contato com o pessoal do Inmet?

**Comment by almeidafab** [comment]
faço sim =)

**Comment by cv** [comment]
Alterado ([e já visível no alpha](http://104.236.231.239/servico/balanco-hidrico-climatico))
