### ISSUE TITLE
Importação palavra-chave legado de um serviço

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/editor-de-servicos#309]
Há um serviço "Biblioteca Digital do Desenvolvimento - BibSPI" que já possui palavras-chave cadastradas no antigo xml, peço que incluam na nova versão da carta para que apareça no editor. Pelo que vi é o único serviço do legado que possui palavra-chave.
Nesse mesmo serviço, tem um texto cadastrado em requisitos, também no legado. Será que ele se encaixaria em documentação? Ou será que não é necessário migrá-lo? O que vocês acham?

**Comment by cv** [comment]
Movido para https://github.com/servicosgovbr/cartas-de-servico/pull/41
