### ISSUE TITLE
Campo opcional não pode ser removido

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#315]
campo de documentação em comum é opcional mas está obrigando o preenchimento de pelo menos um campo

**Comment by gustavo-freitas** [comment]
Não consegui reproduzir localmente esse defeito. Quando removemos uma ou todas documentações associadas, serviço é salvo sem problemas. Cenário também não ocorre em Alpha. Salvar e Publicar não validam se campo de documentação está preenchido ou não. Mensagem de campo obrigatório não é exibida e campos de documentos podem ser removidos.

Aparentemente esse defeito foi corrigido no cartão #218.  Documentação comum consta como opcional no código fonte do Editor (javascript/servico/etapas/documentos.js).

**Comment by gustavo-freitas** [comment]
Entretanto, encontramos um problema relacionado a validação de campos na tela da inclusão do Serviço. **Ambiente:** Local e Alpha 

**Passos para reproduzir:** 
1. Salvar novo serviço somente com Nome
2. Tentar Publicar Serviço 
3. Editor irá reclamar de campos obrigatórios indicando quais campos devem ser preenchidos
4. Preencher todos os campos obrigatórios que o Editor sugere (até palavras-chave)
5. Tentar Publicar Serviço 

**Resultado Atual:**
Editor exibe mensagem de campos obrigatórios mas **não** indica quais campos devem ser preenchidos

**Resultado Esperado:**
Editor exibe mensagem de campos obrigatórios mas continua indicando quais campos devem ser preenchidos

**Validação não ocorre nos seguintes campos obrigatórios:**
- Orgão
- Custo
- Canais
- Tempo (detalhes não são exibidos, por exemplo select não aparece quando usuário seleciona 'Até' ou 'Entre')

**Comment by sahrosa** [comment]
Fechando o cartão conforme combinamos na stand up. @gustavo-freitas você abre os novos cartões?
