### ISSUE TITLE
Visualização de páginas especiais

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#320]
Pré visualização de páginas sendo editadas, e visualização de páginas especiais.

- [ ] Caso seja decidido não ter essa funcionalidade para páginas especiais, é necessário remover os botões de Visualização no editor e na fila de publicação.

**Comment by kchnr** [comment]
@oliviagj, @sahrosa não tenho certeza da prioridade dessa, sendo que as páginas são mais simples, acho que seria no máximo "1", pendendo para "2". O que acham?

**Comment by oliviagj** [comment]
Sugiro deixar 1 por enquanto, para ficar no radar para a próxima
priorização.
