### ISSUE TITLE
Definição de permissões para usuários

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#324]
Pedaço quebrado a partir da #77:

- [x] Definir permissões para usuários

- - - 

Permissões                                       | Administrador | Ponto Focal  | Publicador | Editor  | Usuário não logado
-------------------------------------------------|-------|--------------|------------|---------|----------
Serviço: Criar                           |   ✕   |       ✓      |      ✓     |    ✓    |    ✕
Serviço: Editar e salvar                         |   ✕   |       ✓      |      ✓     |    ✓    |    ✓
Serviço: Publicar alterações                     |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Serviço: Descartar alterações                    |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Serviço: Despublicar                  |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Serviço: Excluir                                 |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Página de órgão: Criar                           |   ✕   |       ✓      |      ✓     |    ✓    |    ✕
Página de órgão: Editar e salvar                 |   ✕   |       ✓      |      ✓     |    ✓    |    ✕
Página de órgão: Publicar alterações             |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Página de órgão: Descartar alterações            |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Página de órgão: Despublicar          |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Página temática: Criar                           |   ✓   |       ✓      |      ✓     |    ✓    |    ✕
Página temática: Editar e salvar                 |   ✓   |       ✓      |      ✓     |    ✓    |    ✕
Página temática: Publicar alterações             |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página temática: Descartar alterações            |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página temática: Despublicar          |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página temática: Excluir                         |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página de á. de interesse: Criar                 |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página de á. de interesse: Editar e salvar       |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página de á. de interesse: Publicar alterações   |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página de á. de interesse: Descartar alterações  |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página de á. de interesse: Despublicar |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página de á. de interesse: Excluir               |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Usuários: Cadastrar usuário                      |   ✓   |       ✓      |      ✓     |    ✕    |    ✕
Usuários: Atribuir papel de Administrador             |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Usuários: Atribuir papel de Ponto Focal                   |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Usuários: Atribuir papel de Publicação                 |   ✕   |       ✓      |      ✕     |    ✕    |    ✕
Usuários: Atribuir papel de Editor               |   ✓   |       ✓      |      ✓     |    ✕    |    ✕
Usuários: Excluir Administrador                          |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Usuários: Excluir Ponto Focal                    |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Usuários: Excluir Publicador                     |   ✓   |       ✓      |      ✕     |    ✕    |    ✕
Usuários: Excluir Editor                         |   ✓   |       ✓      |      ✓     |    ✕    |    ✕

**Comment by sahrosa** [comment]
Oi @almeidafab @mformiga @oliviagj @kchnr ,
quero combinar as regras de permissões do portal com vocês. Temos hoje quatro tipos de usuários, a ideia que estávamos pensando é seguinte:

**Editores:**
  * Editar e salvar serviços 

**Publicadores:**
  * Editar e salvar serviços 
  * Publicar serviços
  * Excluir serviços

**Admin:**
  * Editar e salvar serviços 
  * Publicar serviços
  * Excluir serviços
  * Cadastrar novos editores
  * Cadastrar novos publicadores

**Super admin:**
  * Não são cadastrados através do Editor
  * Editar e salvar serviços 
  * Publicar serviços
  * Excluir serviços
  * Cadastrar novos editores
  * Cadastrar novos publicadores
  * Cadastrar novos admin

O que acham?

**Comment by almeidafab** [comment]
@sahrosa não me lembro mais do motivo para ter dois admins. Não poderia ter um só?

**Comment by oliviagj** [comment]
@almeidafab @sahrosa se não me engano, o admin teria poderes no contexto de um órgão (é a pessoa que a Andrea chama de "ponto focal" de um órgão)

**Comment by oliviagj** [comment]
aliás, acho que devemos deixar claro que publicadores também tem permissões restritas a seu órgão de ativadade @almeidafab @sahrosa

**Comment by sahrosa** [comment]
Concordo @oliviagj!

**Comment by oliviagj** [comment]
@sahrosa, dei uma editada, mas o conteúdo é isso aí, no meu entendimento

**Comment by sahrosa** [comment]
Show! Estou deixando este cartão bloqueado para desenharmos a página quando tivermos a definição fechada entre todos, e também a definição de login.

**Comment by mformiga** [comment]
@sahrosa Seguem nossas considerações:

Sugestões gerais:
* Cadastrar/excluir novos editores
* Cadastrar/excluir novos publicadores

**Editores:**
Permissão abaixo válida para serviços de seu órgão
Editar e salvar serviços

**Publicadores:**
Permissões abaixo válidas para serviços de seu órgão
Editar e salvar serviços
Publicar serviços
Excluir serviços

Sugestões:
* Cadastrar/excluir novos editores

**Admin:**
Permissões abaixo válidas para serviços de seu órgão
Editar e salvar serviços
Publicar serviços
Excluir serviços
Cadastrar novos editores
Cadastrar novos publicadores

Sugestões:
* Alterar nome do perfil para "Ponto focal"

Super admin:
Não são cadastrados através do Editor
Permissões abaixo válidas todos os serviços
Editar e salvar serviços
Publicar serviços
Excluir serviços
Cadastrar novos editores
Cadastrar novos publicadores
Cadastrar novos admin

Sugestões:
* Alterar nome do perfil para "Admin"
* Cadastrar/excluir novos pontos focais ao invés de "Cadastrar novos admin"

Vou enviar esta mensagem para SEGEP também.

**Comment by sahrosa** [comment]
Show @mformiga! Adorei as ideias. Vou atualizar as definições no cartão, e vamos continuar o trabalho de desenhar a página, e enviar pra vocês o quanto antes :)

**Comment by kchnr** [comment]
@sahrosa criar novas páginas, seria considerado uma edição comum? ou teria acesso restrito de alguma forma?

**Comment by kchnr** [comment]
@sahrosa Essa própria página para gerenciar permissões deve ter restrições de acesso certo?

**Comment by sahrosa** [comment]
Oi @kchnr! 
* A página de gerenciamento de permissões não deverá ser vista apenas pelo perfil de editor. 
* Os outros perfis (publicador, ponto focal) verá apenas os itens relacionados ao seu perfil e órgão. 
* O perfil admin poderá visualizar tudo.

**Comment by mformiga** [comment]
@kchnr e @sahrosa Publicador e ponto focal podem buscar todos do seu órgão e depois enxergam todos os editores do seu órgão também.

**Comment by sahrosa** [comment]
Em anexo algumas ideias de como podemos seguir com essa página. Aguardando definições sobre gerid para fechar as decisões do gerenciamento de permissões.

![img_20151005_144702063](https://cloud.githubusercontent.com/assets/2932644/10288586/1942c026-6b70-11e5-9bd0-9ef24fab5ad0.jpg)

**Comment by mformiga** [comment]
@sahrosa @kchnr @almeidafab  Favor acrescentar apenas o e-mail do servidor. Pode ser na mesma célula do nome ou talvez o nome seja um link para os dados do servidor (siape, e-mail, telefone, órgão, etc).

**Comment by sahrosa** [comment]
Super de acordo @mformiga! Havia pensado nisso e esqueci de colocar no desenho. Ficaria mais ou menos assim:

![screen shot 2015-10-05 at 3 29 14 pm](https://cloud.githubusercontent.com/assets/2932644/10289687/ff4e9950-6b75-11e5-9f62-8c4fd30f35f1.png)

**Comment by kchnr** [comment]
@sahrosa, mesmo que definirmos permissões, seria bom também definirmos qual a experiência do usuário em relação às permissões, o que vc acha?

Ex: quando acessar o editor, terão coisas que não estarão visíveis por causa de minhas permissões? ou vai estar visível, mas quando clicar vai aparecer alguma mensagem? quando eu acessar alguma url, que não tenho permissão, o que eu deveria ver?

**Comment by sahrosa** [comment]
Oi @kchnr! Com certeza! Mas acabamos preferindo esperar as definições do gerid pra definir questões de ux, conforme falamos na stand up!

**Comment by sahrosa** [comment]
Aqui tem uma imagem de como ficará a página - podendo haver variações dependendo do gerid:

![gds editor de servicos-permissoes-v1](https://cloud.githubusercontent.com/assets/2932644/10521250/3173fc96-7345-11e5-855e-2dd49b235ed9.jpg)

**Comment by mformiga** [comment]
@sahrosa Acredito que a coluna "Órgão" faz sentido apenas para os usuários com perfil de admin, correto ?

**Comment by sahrosa** [comment]
Isso mesmo @mformiga! :)

**Comment by sahrosa** [comment]
Tela de edição de perfil do usuário. Nem todos os campos serão editáveis, pois isso vai depender das limitações do gerid.

![screen shot 2015-10-19 at 11 09 53 am](https://cloud.githubusercontent.com/assets/2932644/10578624/0048dbae-7652-11e5-957a-e26c0d6e14e5.png)

**Comment by sahrosa** [comment]
Mapa do que cada perfil pode realizar dentro do Editor de Serviços:

![screen shot 2015-10-19 at 4 13 07 pm](https://cloud.githubusercontent.com/assets/2932644/10586720/531f1b8e-767c-11e5-8403-a6147fbe1bce.png)

**Comment by sahrosa** [comment]
Abaixo, questões em aberto quanto a definição de login e permissões.

**Se usarmos o gerid:**
* O gerid utiliza o sistema de órgãos (siorg)? Precisaremos realizar algum de:para ou a relação do órgão ao qual o servidor público faz parte e o órgão em que os serviços são cadastrados no editor? (se precisarmos desse de:para, será que o sentido de utilizar o gerid não se perde?)
* O cadastro será automaticamente realizado quando o usuário se conecta ao editor, no entanto, todos os usuários serão automaticamente cadastrados com o perfil mais básico (editor). Isso me traz uma questão: os usuários saberão que devem pedir para outros usuários darem permissões para eles?

**Se não usarmos o gerid:**
* Se não tivermos uma identificação oficial (como o gerid), teremos que trabalhar com formas de garantir que apenas servidores públicos acessem o editor. Duas formas de fazer isso é:
   * 1: Através do convite de novos usuários. O interessante do convite é que o perfil do usuário já poder ser corretamente setado, uma vez que o convite foi enviado.
   * 2: Através da aprovação de cadastro: a pessoa se cadastra e alguém aprova a sua participação como editor. Esse cenário dá margem de erro para alguém aprovar a participação de pessoas aleatórias.   
* Qual visão o cidadão dentro deste cenário? Me pergunto isso pois se hoje apenas os admins podem ver todos os serviços de todos os órgãos, e os outros perfis podem ver apenas os serviços do seu órgão, a regra seria de que quem não tem órgão, não visualiza nenhum serviço (caso do cidadão)?

**Comment by almeidafab** [comment]
@sahrosa respondendo aos seus questionamentos:

* O gerid utiliza o sistema de órgãos (siorg)? **Estou verificando essa informação.** Precisaremos realizar algum de:para ou a relação do órgão ao qual o servidor público faz parte e o órgão em que os serviços são cadastrados no editor? **Usando o gerid não precisará fazer essa comparação pois o órgão já estará associado ao usuário que está editando, tornando desnecessário escolher o órgão no editor.** (se precisarmos desse de:para, será que o sentido de utilizar o gerid não se perde?)
* O cadastro será automaticamente realizado quando o usuário se conecta ao editor, no entanto, todos os usuários serão automaticamente cadastrados com o perfil mais básico (editor). Isso me traz uma questão: os usuários saberão que devem pedir para outros usuários darem permissões para eles? **os usuários serão informados sobre isso, não será um problema.**
* Se não usarmos o gerid, a opção de convite para novos usuários é a que gostamos mais.

Algumas considerações sobre a imagem dos perfis:

* Na coluna serviços faltou o item **Despublicar** para serviço, órgão, página inicial e área de interesse;
* Na parte dos órgãos colocar "Página do órgãos" ao invés de deixar somente "órgão" para não deixar a impressão que estamos criando (editando, publicando etc) órgão mas sim a página do órgão;
* Sugerimos que o Admin não pode criar, editar, salvar, publicar, excluir e despublicar serviços e páginas especiais. Acreditamos que isso seja papel exclusivamente do órgão. O Admin pode cadastrar e excluir usuários, bem como excluir órgãos e editar perfil de admin;
* O Ponto-focal poderá **Ver serviços de todos os órgãos**, bem como o publicador e o editor;
* O Ponto-focal e o Publicador também poderão excluir órgãos. Entretanto, esses dois não poderão publicar e excluir áreas de interesse;
* Acreditamos também que o ponto-focal pode criar/excluir publicadores e os publicadores podem criar/excluir editores;
* O Editor também pode **ver serviços de todos os órgãos**;
* Acreditamos que todo cidadão é um editor, portanto os dois têm as mesmas permissões.

**Comment by sahrosa** [comment]
Obrigada pelos pontos, @almeidafab! Vou ler tudo e realizar os ajustes conforme necessário!

**Comment by almeidafab** [comment]
@sahrosa respondendo a pergunta que fiquei devendo:
O gerid utiliza o sistema de órgãos (siorg)? **Conversei com o Antônio Fiuza e ele me informou que existem duas tabelas de órgão: uma é o siorg e a outra é uma tabela do siape. O gerid usa a tabela do siape que por sinal utiliza códigos diferentes da tabela do siorg. Mas não há problema nisso porque no gerid existe um "de:para" entre essas duas bases. Ele disse que a tendência é que todos usem a base do siorg mesmo.**

**Comment by almeidafab** [comment]
Oi @sahrosa poderia explicar melhor os itens "Editar perfil de Editor", "Editar perfil de publicador" e "Editar perfil de ponto focal"?

Outro ponto é a divisão em duas partes da linha "Criar, editar e salvar serviço":
*Criar serviço
*Editar e salvar serviço
Com isso, o que vai diferenciar o cidadão do editor será o criação do serviço. O cidadão não poderá criar serviços, somente editar e salvar.

**Comment by sahrosa** [comment]
Oi @almeidafab. "Editar perfil" significa mudar de um perfil para outro. Por exemplo, se os usuários todos entrarem como "editores", deverão ser convidados a serem publicadores ou ponto focal :)

Sobre os ajustes, segue a nova versão ajustada conforme conversado:

![permissoes-editor](https://cloud.githubusercontent.com/assets/2932644/10757496/86ef7352-7c92-11e5-8caa-ec3867c82791.jpg)

**Comment by almeidafab** [comment]
Oi @sahrosa  faltou o item **Despublicar** para serviço, órgão, página especial e área de interesse. Quem possui permissão para publicar esses itens também poderia despublicar.

**Comment by sahrosa** [comment]
Oi @almeidafab! 

Realmente faltou despublicar "serviço" e "página especial", vou incluir isso!

Mas você acha que faz sentido despublicar "órgão" e "área de interesse"? Porque essas página se relacionam com os serviços relacionados a esses órgãos e essas áreas de interesse. O que você acha?

**Comment by almeidafab** [comment]
@sahrosa na verdade, a funcionalidade não é para despublicar órgão e área de interesse, mas sim despublicar **página** de órgão e **página** de área de interesse. Como existe a funcionalidade para publicar esses dois itens, não seria coerente a despublicação? Isso não irá impactar no cadastro de órgãos e áreas de interesse.

Sugiro renomear de "Órgão" para "Página de Órgão" e de "Área de interesse" "Página de área de interesse", o que acha?

**Comment by sahrosa** [comment]
Legal @almeidafab! Conversamos aqui @kchnr e eu, e achamos que na verdade estaremos apenas despublicando o conteúdo do órgão e da área de interesse, pois a página em si precisa estar sempre no ar, dado que estas páginas trazem os serviços relacionados, e aparecem na listagem de órgão, listagem de áreas de interesse (menu) e também na página do serviço.

O que acha/

**Comment by sahrosa** [comment]
Podemos fechar este cartão @oliviagj @gustavo-freitas? Uma vez que existem outros cartões que surgiram a partir desse?

**Comment by oliviagj** [comment]
quais cartões, @sahrosa? entendo que esse continua tendo seu próprio escopo e ainda precisamos termina-lo.

**Comment by sahrosa** [comment]
Ok!

**Comment by sahrosa** [comment]
Ok!

**Comment by sahrosa** [comment]
Linkando cartões relacionados a este: #332 #333 #334

**Comment by oliviagj** [comment]
Olha só:
@mformiga e @almeidafav, por favor verifiquem se ficou algum problema
@pedrombl, @sahrosa: por favor, perguntem qualquer dúvida

Permissões                                       | Admin | Ponto Focal  | Publicador | Editor  | Sem login
-------------------------------------------------|-------|--------------|------------|---------|----------
Serviço: Criar serviço                           |   ✕   |       ✓      |      ✓     |    ✓    |    ✕
Serviço: Editar e salvar                         |   ✕   |       ✓      |      ✓     |    ✓    |    ✓
Serviço: Publicar alterações                     |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Serviço: Descartar alterações                    |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Serviço: Despublicar alterações                  |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Serviço: Excluir                                 |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Página de órgão: Criar                           |   ✕   |       ✓      |      ✓     |    ✓    |    ✕
Página de órgão: Editar e salvar                 |   ✕   |       ✓      |      ✓     |    ✓    |    ✕
Página de órgão: Publicar alterações             |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Página de órgão: Descartar alterações            |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Página de órgão: Despublicar alterações          |   ✕   |       ✓      |      ✓     |    ✕    |    ✕
Página temática: Criar                           |   ✓   |       ✓      |      ✓     |    ✓    |    ✕
Página temática: Editar e salvar                 |   ✓   |       ✓      |      ✓     |    ✓    |    ✕
Página temática: Publicar alterações             |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página temática: Descartar alterações            |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página temática: Despublicar alterações          |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página temática: Excluir                         |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página de á. de interesse: Criar                 |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página de á. de interesse: Editar e salvar       |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página de á. de interesse: Publicar alterações   |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página de á. de interesse: Descartar alterações  |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página de á. de interesse: Despublicar alterações|   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Página de á. de interesse: Excluir               |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Usuários: Cadastrar usuário                      |   ✓   |       ✓      |      ✓     |    ✕    |    ✕
Usuários: Atribuir papel de Admin                |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Usuários: Atribuir papel de PF                   |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Usuários: Atribuir papel de Pub                  |   ✕   |       ✓      |      ✕     |    ✕    |    ✕
Usuários: Atribuir papel de Editor               |   ✓   |       ✓      |      ✓     |    ✕    |    ✕
Usuários: Excluir Admin                          |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Usuários: Excluir Ponto Focal                    |   ✓   |       ✕      |      ✕     |    ✕    |    ✕
Usuários: Excluir Publicador                     |   ✓   |       ✓      |      ✕     |    ✕    |    ✕
Usuários: Excluir Editor                         |   ✓   |       ✓      |      ✓     |    ✕    |    ✕

**Comment by mformiga** [comment]
Sugestões:
- Ao invés de "Criar serviço" colocaria "Criar" da mesma forma que está nos
demais.
- Ao invés de "Despublicar alterações" colocaria "Despublicar" em todas as
ocorrências.


2015-11-16 15:07 GMT-02:00 Olivia Janequine <notifications@github.com>:

**Comment by oliviagj** [comment]
@sahrosa feito :-)

**Comment by oliviagj** [comment]
Renomeamos papel "Cidadão" para "Usuário não logado"

**Comment by oliviagj** [comment]
@mformiga, se você estiver OK, por favor, feche este cartão.

**Comment by mformiga** [comment]
De acordo.
