### ISSUE TITLE
Cadastro de usuários e suas permissões no Redis

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#331]
Redis vai permitir gerenciamento de permissões sem a necessidade de alterar configurações ou reiniciar serviços, apenas a partir de uma tela para gerencia de configurações.
- [ ] Adicionar Redis às dependencias de infraestrutura no docker, para fácil instalação e Deploy
- [ ] Novos usuários que fizerem o login devem ser cadastrados com permissões de “Editor” no Redis
- [ ] Permissões devem ser carregadas a partir do Redis
- [ ] Permissões já existentes (arquivo configuração) devem ser migradas para o Redis

Alguns detalhes técnicos:
- adicionar um Redis à infra pra ter dados persistentes (precisa mapear o volume pro lugar certo la no docker, etc)
- adicionar uma hash de email -> permissão no redis
- aumentar o objeto UserProfile pra ter esse conjunto de permissões também
- adicionar todos os emails novos (quando alguem se loga pela primeira vez) nesse hash
- migrar caches do editor pra redis (o RedisCache é bem mais facil de inspecionar que o guava que a gente usa hoje)
- fechar todos os metodos relevantes do RepositorioGit ou ConteudoVersionado às permissões dos usuários (baba de fazer no spring security) bolar um endpoint pra verificar as permissoes do usuario (se bobear pode até pegar carona no /editar/api/ping, que ja volta o profile mesmo)
- adicionar ifs na UI pra nao mostrar funcionalidades que o usuario nao tem acesso bolar uma telinha pra dar/remover permissões pros usuários (#324), essa tela também deve ter restrições de acesso

**Comment by gustavo-freitas** [comment]
Caso integração com GERID funcionar completamente, não iremos utilizar REDIS. Assim, card não é mais válido.

**Comment by gustavo-freitas** [comment]
Considerando que decidimos armazenar usuários e permissões em um banco de dados relacional (postgresql), esse card não faz mais sentido. Ok @kchnr ?

**Comment by sahrosa** [comment]
Vamos documentar e fechar este cartão @gustavo-freitas @pedrombl

**Comment by gustavo-freitas** [comment]
Iremos implementar uma solução interna que não irá utilizar Redis ou qualquer banco em memória. Essa solução será segura, utilizará SSL e criptografia de senhas diretamente no banco de dados. O banco será relacional (Postgresql). O trabalho relacionado com esse esforço está descrito nos seguintes cartões.

**Autenticação:**
- #407 
- #406 
- #405 
- #404 
- #403 
- #376 
- #297

**Usuários e Permissões:**
- #432 
- #433 
- #337
- #334 
- #333
