### ISSUE TITLE
Login e integração com o sistema de login do Governo, o GERID

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#335]
Necessidades:
- [ ] Será utilizado a parte de Login do GERID
- [ ] Conseguir acesso ao Wiki, ou ao menos, pedir para baixarem manualmente os arquivos de aplicações exemplo que estão na conversa abaixo, e enviarem para usarmos como exemplo
- [ ] Ambiente de desenvolvimento pela DTI dentro do SERPRO (Cobrar como está isso)
- [ ] Ambiente dev com acesso aos serviços do GERID
- [ ] Criar usuários para desenvolvedores no GERID para poder fazer os testes de integração

Alguns detalhes já conversados abaixo:

> Sobre as funcionalidades:
GERID é apenas um sistema de autenticação ou também armazena e gerencia permissões e acesso para as aplicações que integram com o GERID?
Pode funcionar das duas formas.  Ele é um sistema AAA (autenticação, autorização e accounting).  Numa integração "completa", gerencia autenticação, permissões e acesso para as aplicações. 
Por outro lado, caso se deseje somente autenticação, também é possível. 
Sobre como integrar e usar o GERID e suas funcionalidades:
Existe uma biblioteca pronta (JAR) que podemos utilizar e integrar facilmente?
A integração é realizada via um componente do GERID que via acoplado à aplicação (componentes ASDS). É essencialmente um JAR + um conjunto de configurações.

A documentação dá a entender que algumas dessas bibliotecas podem estar em um repositório maven interno, ao invés de um repositório público. Será possível acessar esse repositório de fora do governo?
Vamos buscar viabilizar este acesso.
A forma de integração é um WebService ou serviço REST que possamos acessar? Ou alguma forma de autenticação “OAuth2”?
É realizado via ASDS.
Se for WebService, é possível ter acesso às WSDLs para gerarmos os serviços no nosso projeto?
Quais os requisitos necessários para conseguirmos integrar com o GERID? Será necessário algum um cadastro para pegar um TOKEN para que nossa aplicação utilize o GERID?
Existe algum exemplo aplicação ou modulo já integrado ao GERID que poderíamos ter acesso ao código, e utilizar como exemplo de integração?
Os links para acessar e fazer download da aplicação parceira de exemplo são:
https://wiki.sigepe.csd.serpro/index.php?title=IntegracaoGerid#Aplica.C3.A7.C3.A3o_de_Refer.C3.AAncia
https://wiki.sigepe.csd.serpro/images/3/3f/GeridTesteApp_a_2_17_2.zip

Acesso a aplicação parceira de exemplo em testes:
https://aplic-teste.gerid.csd.serpro/GeridTesteApp_a/pages/restrict/index.xhtml

Temos acesso à documentação da API do GERID?
Via manual de integração na WIKI.

Infra:
Quais IPs e Portas nossa aplicação precisa acessar?
Existe algum ambiente de testes ou homologação no qual conseguimos testar a autenticação?
Conseguimos acesso à servidores de testes ou homologação do GERID a partir de agora, para o desenvolvimento?
O GERID possui ambientes de testes e homologação.  Na medida em que evoluirmos no projeto, tem-se que solicitar ao SERPRO os ajustes nas configurações de infra (liberações de firewall, etc) para permitir o acesso a partir do ambiente do SERVICOS.GOV.

**Comment by oliviagj** [comment]
@kchnr e @gustavo-freitas, acho que vale documentar a decisão de não usar o Gerid aqui e depois fechar o cartão, o que vocês acham?

**Comment by oliviagj** [comment]
@kchnr e @gustavo-freitas, acho que vale documentar a decisão de não usar o Gerid aqui e depois fechar o cartão, o que vocês acham?

**Comment by gustavo-freitas** [comment]
Sim, documento essa decisão aqui.

2015-11-09 13:57 GMT-02:00 Olivia Janequine <notifications@github.com>:

**Comment by sahrosa** [comment]
Cartão será fechado após documentação da decisão @gustavo-freitas? Ou já podemos fechar?

**Comment by gustavo-freitas** [comment]
Vamos documentar primeiro. Deixamos o cartão aberto.
