### ISSUE TITLE
Débitos técnicos gerados pelo cartão #77

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#336]
migrar alguns toggles que podem ser necessarios ligar/desligar em runtime sem reiniciar o stack pro redis tb
migrar pds-persistente do portal/elasticsearch pro redis
migrar caches do editor pra redis (o RedisCache é bem mais facil de inspecionar que o guava que a gente usa hoje)
migrar caches do portal pra redis (idem acima)
corrigir o req.remoteUser nos logs (tá vindo vazio desde que a gente migrou pro OAuth)

**Comment by gustavo-freitas** [comment]
Considerando que não iremos mais utilizar Redis, esse cartão será fechado.
