### ISSUE TITLE
Conexão é perdida e todos as ações realizadas são perdidas junto

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#344]

**Comment by cv** [comment]
Contexto?



- cv

**Comment by sahrosa** [comment]
1. Criei serviço no localhost
1. Serviço é salvo normalmente
1. Serviço aparece na lista de serviços
1. Editando serviço e mensagem de conexão com servidor perdida começa a aparecer
1. Reiniciei o local e o serviço criado não existe mais

**Comment by gustavo-freitas** [comment]
Tentei reproduzir localmente esse problema e não consegui. Isso continua sendo um problema para alguém?

**Comment by sahrosa** [comment]
Este bug está relacionado ao login pelo google. Quando modificarmos a forma de login, este problema pode desaparecer.

**Comment by gustavo-freitas** [comment]
Considerando que decidimos desenvolver uma solução interna para autenticação. Esse problema não deverá ocorrer no futuro. Fechando cartão.
