### ISSUE TITLE
A fila de publicação ainda não está funcionando

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#356]
Operações que devem funcionar:
  - [x] editar
  - [x] criar novo serviço
  - [x] publicar
  - [x] criar nova página
  - [x] visualizar

**Comment by gustavo-freitas** [comment]
Decidimos com Maurício e Fabrício chamar a 'fila de publicação' de 'controle de publicação'. Além disso, temos que definir quais papéis vão poder realizar esse controle dentro da aplicação. Uma possibilidade seria utilizar um ícone  na tela de lista serviços do editor.

**Comment by sahrosa** [comment]
Podemos passar este cartão adiante, certo @gustavo-freitas?

**Comment by gustavo-freitas** [comment]
@sahrosa está claro exatamente o que foi feito nesse cartão? Não tenho certeza que isso deva ir adiante, sem saber o que fizemos de mudanças.

**Comment by sahrosa** [comment]
Entendo esse cartão mais como um checklist do que precisava estar funcionando na lista, solicitado pelo Fabricio/Mauricio por e-mail.

**Comment by gustavo-freitas** [comment]
Certo. Entendi @sahrosa. Concordo em passar adiante. Só uma pergunta: temos esse e-mail para adicionar um contexto para o cartão?

**Comment by sahrosa** [comment]
Sim! Encaminhei pra ti!
