### ISSUE TITLE
A despublicação ainda não está funcionando

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#357]
Tirar o serviço do ar do portal de serviços, mas ainda ser possível editar. Diferente de "deletar" que perde-se todas as alterações tanto no portal de serviços, como a habilidade de editar.

Despublicar na página do serviço:

![image](https://cloud.githubusercontent.com/assets/2932644/10648580/e9574886-781d-11e5-937e-df62ce099247.png)

Despublicar na lista de serviços:

![image](https://cloud.githubusercontent.com/assets/2932644/10648679/9920a172-781e-11e5-8bef-aebeec901d03.png)

Ícone: fa-pencil

**Comment by kchnr** [comment]
@sahrosa, como funcionaria, mais um botão de ação na lista da tela inicial?

**Comment by sahrosa** [comment]
Acredito que sim, resolveria o problema! Mas não sei se concordo com a prioridade 0 deste cartão, pois isto não era algo que havia sido projetado inicialmente. 

O que acham @gustavo-freitas @oliviagj @kchnr ?

**Comment by sahrosa** [comment]
Incluí imagens de como deveria ser essa "despublicação". Acho o termo "despublicar" bem estranho, alguma sugestão melhor pessoal?

**Comment by sahrosa** [comment]
Termos sugeridos: "desativar" ou "tirar do ar"

**Comment by sahrosa** [comment]
Estou fechando este cartão pois o mesmo está contemplado no #393 ok, @almeidafab @mformiga @gustavo-freitas ?
