### ISSUE TITLE
Testar situações de concorrência do Editor de serviços

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#359]
Cenários:
- Abrir lista inicial de serviços, clicar na "lixeira" para deletar um serviço e confirmar, antes de terminar a primeira operação (enquanto estiver processando), fazer o mesmo para um outro serviço qualquer. Ocorrem erros no servidor.

- Usuário publica novo serviço no Editor (instância número um é utilizada). Branch local criada. Push realizado. Informações do serviço salvas no Github.
Usuário lista os serviços disponíveis no Editor (instância número 2 é utilizada). Instância número dois não possui informações do serviço criado. Branch não existe localmente.

**Comment by sahrosa** [comment]
Estes cenários estão sendo tratados no cartão #396
