### ISSUE TITLE
Mensagem de feedback ao publicar um serviço

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#363]
Ao publicar o serviço, alterar a mensagem para “O serviço foi publicado com sucesso. Dentro de alguns minutos poderá ser encontrado no Portal de Serviços (www.serviços.gov.br)”. O sistema deve voltar para a tela dos serviços;

**Comment by almeidafab** [comment]
@kchnr o texto não está conforme o cartão e ao publicar o usuário permanece ainda na mesma página.

**Comment by sahrosa** [comment]
Olá @almeidafab! Nós colocamos a mensagem inicial apenas (O serviço foi publicado com sucesso), para manter o padrão entre as restantes, pois a mensagem sugerida estava longa. E mantemos o usuário na página após a publicação, para que o mesmo não perca a referência de onde e o que estava fazendo. Leva-lo para a página inicial de todos os serviços pode facilmente gerar uma falta de compreensão. O ideal seria testarmos esse comportamento, e se entendermos que é melhor mandar para a página incial, aí sim manda-lo.

Por enquanto sugiro que a experiência mantenha-se como está!

**Comment by gustavo-freitas** [comment]
Este cartão ainda não foi finalizado, precisamos de alinhamento para determinar o melhor comportamento da funcionalidade.

**Comment by gustavo-freitas** [comment]
Cartão #384 associado.

**Comment by sahrosa** [comment]
Revisamos os cartões que estão na tabela de prioridades, e percebemos que este cartão não é uma prioridade no momento. Estamos colocando o mesmo na label "fora de escopo".

**Comment by gustavo-freitas** [comment]
@almeidafab @mformiga a mensagem de publicação foi incluída no Editor. Por favor, revisem. 
Além disso, conforme comentários da @sahrosa e considerando que tínhamos acertado anteriormente que as questões de voltar para lista de páginas do Editor (cartão #384) não eram prioritárias, considero o trabalho nesse cartão encerrado.
