### ISSUE TITLE
Esconder ícone "check ok"

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#365]
Enquanto cartão #196 não for realizado, não podemos mostrar o check "ok" ao lado das áreas do editor no menu lateral da esquerda.

**Comment by glauberramos** [comment]
Pessoal acreditamos que esse cartão está pronto, podemos passar para homologação @almeidafab @mformiga @gustavo-freitas?

**Comment by gustavo-freitas** [comment]
Ok @glauberramos.

**Comment by oliviagj** [comment]
@gustavo-freitas precisamos verificar com o pessoal da DGE se o #196 caiu mesmo. Como chegamos a esta conclusão?

**Comment by gustavo-freitas** [comment]
De acordo com conversa com @almeidafab @cevmelo a funcionalidade em questão não é prioritária.
