### ISSUE TITLE
Revisar feedback de ações (salvar, excluir, publicar)

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#375]
Atualmente está assim: 

* Salvar = spinner
* Publicar = nada
* Alterar nome = spinner

Percebemos que se o usuário editar durante algum procedimento, comportamentos inesperados podem acontecer, como perder a edição. 

Precisamos decidir se iremos bloquear a página inteira ou continuar com "micro feedbacks".

**Comment by oliviagj** [comment]
veio do #339, @sahrosa?

**Comment by sahrosa** [comment]
Veio de uma percepção do @kchnr e minha! Mais uma questão de padronização, mas nada urgente :)

**Comment by oliviagj** [comment]
apareceu aqui também :-)

**Comment by sahrosa** [comment]
Fechando este cartão, já que os botões de publicação foram modificados.

**Comment by oliviagj** [comment]
@sahrosa, estou confusa, esse cartão não era sobre os botões de publicação :(

**Comment by sahrosa** [comment]
Era sobre o feedback dos botões de ação, o único que estava fora do padrão era o botão de "publicar" que não existe mais. Por isso fechei o cartão. Ficou mais claro @oliviagj?

**Comment by oliviagj** [comment]
Ficou sim. Só para garantir: sabemos e estamos seguros de que neste momento os feedbacks de ação estão ok?

**Comment by sahrosa** [comment]
A princípio sim: 
* os botões ficam bloqueados enquanto alguma ação está acontecendo
* temos as mensagens de feedback quando a ação é concluída
* loading quando a ação está sendo realizada

Prefere reabrirmos o cartão pra não esquecer disso, @oliviagj?

**Comment by oliviagj** [comment]
Não, tudo bem, fica fechado e com essa nossa conversa registrada :-)
