### ISSUE TITLE
Melhorar UI de Criar Página

### ISSUE THREAD

**Issue by gustavo-freitas** [servicosgovbr/editor-de-servicos#383]

**Comment by kchnr** [comment]
Muito aberto, tem algum feedback de que parte exatamente está ruim? Para sermos mais assertivos na hora de melhorar.

**Comment by gustavo-freitas** [comment]
Maurício acredita que podemos aproveitar melhor o espaço em branco da tela de criação de Páginas. Olívia tem algumas ideias para ilustrar melhor. Nada de implementação pesada, só detalhes de UI.

**Comment by sahrosa** [comment]
Podemos melhorar, com certeza! Mas este cartão está no escopo ou fechamos @oliviagj @gustavo-freitas ?

**Comment by gustavo-freitas** [comment]
Fora do escopo nesse momento.
