### ISSUE TITLE
Campos com erros não são identificados na notificação de erro

### ISSUE THREAD

**Issue by cevmelo** [servicosgovbr/editor-de-servicos#413]
Após já ter salvo o formulário e clicar no botão “publicar” o portal exibe a seguinte mensagem “Serviço ainda contém erros.”, contudo os respectivos campos com erros não são exibidos.

http://104.236.231.239.xip.io/editar/servico/carlos-teste

**Comment by gustavo-freitas** [comment]
@cevmelo Já existem cards para esse problema. São eles: #394 #314
