### ISSUE TITLE
Tamanho combo “Selecione o Órgão”

### ISSUE THREAD

**Issue by cevmelo** [servicosgovbr/editor-de-servicos#416]
A combo “Selecione a Área de Interesse” apresenta um tamanho muito pequeno.

http://104.236.231.239.xip.io/editar/area-de-interesse/novo

![3](https://cloud.githubusercontent.com/assets/15729050/11062128/7fb19d16-8793-11e5-802c-0274c449404d.JPG)

**Comment by cevmelo** [comment]
Continua

**Comment by glauberramos** [comment]
Duplicação da #321, vou fechar esse cartão
