### ISSUE TITLE
Link quebrado em "Outras Informações"

### ISSUE THREAD

**Issue by cevmelo** [servicosgovbr/editor-de-servicos#423]
1- Entrar na página http://104.236.231.239.xip.io/servico/carlosteste2?pk_campaign=busca 

2- Clicar no link http://104.236.231.239.xip.io/orgao/ministerio-do-planejamento-orcamento-e-gestao-mp o portal apresenta página de erro.

![tp002](https://cloud.githubusercontent.com/assets/15729050/11099336/e257713a-8891-11e5-80c7-df859135e64d.JPG)

@gustavo-freitas @sahrosa

**Comment by gustavo-freitas** [comment]
Cartão relacionado com #493 e #421.

**Comment by sahrosa** [comment]
Fechando cartão pois é duplicada com a #481.
