### ISSUE TITLE
Criar meu usuário no Editor do Portal

### ISSUE THREAD

**Issue by cevmelo** [servicosgovbr/editor-de-servicos#431]
Favor criar meu usuário no Editor do Portal

e-mail: carlos-eduardo.melo@planejamento.gov.br

**Comment by gustavo-freitas** [comment]
Estamos criando o usuário @cevmelo.

**Comment by cevmelo** [comment]
OK. obrigado.

**Comment by gustavo-freitas** [comment]
Usuário criado @cevmelo.
