### ISSUE TITLE
Serviço despublicado não está sendo mostrado na lista de serviços

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#440]
Após despublicar o /servico-de-teste, master é removida e branch é criada, mas não está sendo mostrada na lista de serviços.

**Comment by kchnr** [comment]
@sahrosa eu não consegui mais reproduzir esse problema com nenhum serviço do cartas-de-teste, vc ainda consegue?

**Comment by sahrosa** [comment]
Pra mim parece ok também @kchnr. Só gostaria de testar em alpha (que foi onde o problema aconteceu originalmente) antes de fecharmos esse cartão!

**Comment by sahrosa** [comment]
Oi @kchnr!
Estava testando agora em alpha e não encontrei o /servico-de-teste na lista de serviços... então acho que o problema continua persistente.

**Comment by sahrosa** [comment]
Fechando o cartão pois o problema parou de acontecer @gustavo-freitas!
