### ISSUE TITLE
Erro ao digitar CPF inexistente na confirmação de cadastro ou troca de senha

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#468]
Ao digitar um CPF inexistente na confirmação de cadastro ou trocar de senha, o usuário é levado para uma página de "usuário não existe" conforme imagens abaixo:

<img width="944" alt="screen shot 2015-12-02 at 7 54 04 pm" src="https://cloud.githubusercontent.com/assets/2932644/11545482/b2950504-992e-11e5-958b-1ae53c4c2356.png">

Mensagem de erro atual, que pode ser substituida por um alertify.
<img width="247" alt="screen shot 2015-12-02 at 7 50 39 pm" src="https://cloud.githubusercontent.com/assets/2932644/11545391/49f4faa4-992e-11e5-98af-51f6bc8cadcf.png">

**Comment by sahrosa** [comment]
Tu acha que esse poderia ser resolvido com um erro de preenchimento, @glauberramos? Acho que já seria bem melhor né? Tipo ao preencher um CPF inválido mostrar o erro "CPF inválido" e mesma coisa pros erros de senha repetida errada ou de senha menor que 8 caracteres

**Comment by glauberramos** [comment]
@sahrosa eu acredito que esse erro esteja sendo causado pelo problema do https, agora logo iremos fazer deploy de uma versão sem https em alpha e vou testar pra ver se ainda está acontecendo.

Quando tu identificou esse erro foi em alpha ou local?

**Comment by glauberramos** [comment]
O erro que apareceu para mim em alpha foi esse, acho que podemos fechar esse card @sahrosa 

<img width="820" alt="screen shot 2015-12-03 at 4 47 38 pm" src="https://cloud.githubusercontent.com/assets/559434/11570291/a50aeac0-99dd-11e5-93c6-54da3ef8efab.png">

**Comment by sahrosa** [comment]
Fato @glauberramos :+1: 

Estou fechando este cartão. Obrigada!
