### ISSUE TITLE
Ao excluir órgão pelo github continua aparecendo no Editor

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/editor-de-servicos#490]
Ao excluir um órgão diretamente pelo github, ele não é excluído da lista do Editor. O órgõa continua sendo exibido como "despublicado".

**Comment by almeidafab** [comment]
O órgão que excluí foi a Funai

**Comment by gustavo-freitas** [comment]
@almeidafab em qual repositório tu fizeste essa mudança? Lembra que o ambiente de desenvolvimento está apontando para cartas-de-teste, não cartas-de-serviço. Não existe FUNAI em cartas-de-teste.

**Comment by almeidafab** [comment]
@gustavo-freitas eu excluí no cartas-de-teste mesmo: https://github.com/servicosgovbr/cartas-de-teste/commit/30502c055c04de52f905d3b4937b87b620c21234
Até o final do dia de ontem ainda estava aparecendo. Hoje pela manhã quando fui checar, estava excluído. Será que a exclusão só foi efetivada depois que vc fez o deploy?

**Comment by gustavo-freitas** [comment]
@almeidafab existe essa possibilidade, estamos investigando.

**Comment by gustavo-freitas** [comment]
@almeidafab fiz alguns testes no repositório cartas-de-teste:

- https://github.com/servicosgovbr/cartas-de-teste/commit/2aa5cf08fa4684fef3507b63e5ca60d0d5cd5508
- https://github.com/servicosgovbr/cartas-de-teste/commit/7f90ab087103455287183fee7d69c84488efbf37
- https://github.com/servicosgovbr/cartas-de-teste/commit/8aa6387e8950a27f989f8e32210295a703ce64f4

Então, o órgão continuou aparecendo como despublicado, pois tu deletou somente master. Se tu tivesse deletado a branch também, conforme esperado, tu não iria mais conseguir acessar o serviço no Editor. De qualquer forma, para sumir totalmente com o serviço da lista do Editor, atualmente é necessário reiniciar a aplicação. Por fim, entendo que poderíamos aprimorar esse comportamento, mas não vejo como algo prioritário, especialmente considerando que o Editor foi construído para fazer operações mais avançadas com os serviços. Por favor, fica à vontade para colocar tua perspectiva.

**Comment by gustavo-freitas** [comment]
@almeidafab lembrando que no Portal de Serviços, o serviço excluído desaparece automaticamente sem nenhuma intervenção manual.
