### ISSUE TITLE
Ao preencher as informações de serviços  na tag "Tempo estimado para realizar esse serviço", e seleciona o combo "Entre" o sistema estar permitindo colocar valor negativo no 2º período. O certo seria permitir somente valor positivo e maior que o primeiro período.

### ISSUE THREAD

**Issue by josselmo** [servicosgovbr/editor-de-servicos#499]
Ao preencher as informações de serviços 
na tag "Tempo estimado para realizar esse serviço", e seleciona o combo "Entre" o sistema estar permitindo colocar valor negativo no 2º período. O certo seria permitir somente valor positivo e maior que o primeiro período.

**Comment by gustavo-freitas** [comment]
@josselmo já havíamos conversado com o @almeidafab sobre esse cenário. Decidimos, em conjunto, que Isso não é uma prioridade e movemos para conversar futuras. Por favor, ver #459 e #473.

**Comment by josselmo** [comment]
OK, @gustavo-freitas Valeu.
