### ISSUE TITLE
Adicionar campo na Etapas para realização deste serviço

### ISSUE THREAD

**Issue by caduvieira** [servicosgovbr/editor-de-servicos#50]
Sugiro modificar o "Etapas para a realização deste serviço"

Adicionar um campo como:
"Nessa etapa o solicitante necessita interagir com outro órgão?"
[] Sim
[] Não

Com isso nos poderíamos identificar mais facilmente pontos de interação entre os órgãos que utilizam o cidadão/empresa como 'office boy' para trazer e levar certidões/declarações e afins. E poder melhorar esse serviço retirando interações desnecessárias.

Não consegui pensar em uma pergunta mais clara...

**Comment by cv** [comment]
Fora de escopo, por enquanto.
