### ISSUE TITLE
Ao criar uma página temática, independente do perfil do usuário, os dados não são apresentado após a conclusão da ação salvar.   https://dev.servicos.gov.br/editar/pagina-tematica/novo

### ISSUE THREAD

**Issue by josselmo** [servicosgovbr/editor-de-servicos#500]
Ao criar uma página temática, independente do perfil do usuário, os dados não são apresentado após a conclusão da ação salvar. 

https://dev.servicos.gov.br/editar/pagina-tematica/novo

**Comment by gustavo-freitas** [comment]
@josselmo esse defeito já foi criado anteriormente, ver #498. Vou fechar esse defeito.
