### ISSUE TITLE
Problema em carregar os serviços no Chrome

### ISSUE THREAD

**Issue by josselmo** [servicosgovbr/editor-de-servicos#503]
Problema em carregar os serviços no Chrome.

**Comment by gustavo-freitas** [comment]
@josselmo pode nos passar mais detalhes do cenário encontrado?

**Comment by gustavo-freitas** [comment]
@josselmo caso a tua descrição inicial seja relacionada com abrir serviços no Editor, utilizando o Chrome, não consegui reproduzir esse cenário. Por favor, mais detalhes são necessários.

**Comment by gustavo-freitas** [comment]
@josselmo esse problema está sendo corrigido no cartão #522. Não existe necessidade de criar cartões repetidos. Irei fechar esse cartão.
