### ISSUE TITLE
Problema em carregar o serviço no Firefox v43.0.4

### ISSUE THREAD

**Issue by josselmo** [servicosgovbr/editor-de-servicos#505]
Problema em carregar o serviço no Firefox v43.0.4.

**Comment by gustavo-freitas** [comment]
@josselmo qual problema especificamente? qual serviço? A página fica em branco? Só acontece nessa versão do Firefox? Por favor, precisamos de mais detalhes para entender o cenário.

**Comment by josselmo** [comment]
@gustavo-freitas Após logar no Editor, o sistema não apresenta a lista dos serviços. Fica um mensagem carregando...
![erro](https://cloud.githubusercontent.com/assets/16206739/12198447/2819e1a2-b5f7-11e5-85ca-d4b5424a3e2f.png)

**Comment by gustavo-freitas** [comment]
@josselmo Ok. Esse problema está sendo corrigido no cartão #522. Não existe necessidade de criar cartões repetidos. Irei fechar esse cartão.
