### ISSUE TITLE
Na página de lista de usuário o email está cortado.

### ISSUE THREAD

**Issue by josselmo** [servicosgovbr/editor-de-servicos#508]
Na página de lista de usuário o email está cortado.
Conforme imagem abaixo:
![erro](https://cloud.githubusercontent.com/assets/16206739/12203880/6ae128d0-b618-11e5-8f2e-a168839a2461.png)

**Comment by gustavo-freitas** [comment]
@josselmo isso não é um problema, mas sim uma funcionalidade que implementados quando o e-mail é muito grande. Sendo assim, não vejo nenhuma alteração necessária para esse cartão.

**Comment by josselmo** [comment]
OK
