### ISSUE TITLE
Ao descartar um serviço não estar recarregando a página após o descarte.

### ISSUE THREAD

**Issue by josselmo** [servicosgovbr/editor-de-servicos#510]
Segue o exemplo:
![erro](https://cloud.githubusercontent.com/assets/16206739/12207379/69972e56-b62d-11e5-9aa2-1dd74408143a.png)

Após descartar aparece a mensagem e as informações não são carregado, somente quando atualiza a página com F5
![erro](https://cloud.githubusercontent.com/assets/16206739/12207482/f45d6a64-b62d-11e5-8291-d37e014ab444.png)

**Comment by gustavo-freitas** [comment]
@josselmo você já abriu anteriormente o mesmo cenário no cartão #531. É melhor ficarmos somente com um cartão, assim conseguimos nos organizar melhor. Estou fechando esse cartão.
