### ISSUE TITLE
Repensar o modelo de oficina do editor a partir do feedback do MPOG

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#52]
A partir do modelo de oficina+laboratório de inovação, definir uma estratégia para testar o editor.

**Comment by caduvieira** [comment]
@sahrosa Você já viu o TypeForm? Eu acho bem agradável e rápido de responder. http://www.typeform.com/examples/

**Comment by sahrosa** [comment]
Oi @caduvieira! Simmm, o typeform é demais! O nosso primeiro experimento com o editor foi aqui ó: https://cv2.typeform.com/to/xAD6mP

É uma super referência pra gente!
