### ISSUE TITLE
Escolher órgão responsável automaticamente

### ISSUE THREAD

**Issue by cv** [servicosgovbr/editor-de-servicos#55]
Divisão da #43

**Comment by sahrosa** [comment]
Como o servidor pode estar em um órgão, mas mudando pra outro, por exemplo, podemos mostrar uma sugestão automática de órgão responsável, mas dar a possibilidade dele decidir qual realmente é. Concordam? :)

**Comment by sahrosa** [comment]
O que acham do comentário acima @cv @jeankirchner @oliviagj @mformiga @almeidafab?

**Comment by jeankirchner** [comment]
Faz sentido para mim.

**Comment by almeidafab** [comment]
@sahrosa eu e @mformiga conversamos com o pessoal do webservice do siape e eles nos disseram que quando alguém muda de órgão e essa mudança é oficializada, a atualização é na hora. Então, com isso achamos que não é necessário a opção de escolher o órgão, podemos deixar que essa verificação seja feita automaticamente usando o webservice. O que vocês acham?

**Comment by sahrosa** [comment]
Legal @almeidafab @mformiga. Acho que podemos deixar a verificação automática, sim! @cv alguma preocupação ou sugestão quanto à isso?

**Comment by oliviagj** [comment]
matado até que se prove o contrário. nesse caso, criamos um novo.
