### ISSUE TITLE
Melhorias no feedback

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#58]
De acordo com o [decreto 6932] (http://www.planalto.gov.br/ccivil_03/_ato2007-2010/2009/decreto/d6932.htm):

> V ­ procedimentos para receber, atender, gerir e responder às sugestões e reclamações;** temos posteriormente que melhorar nosso feedback

**Comment by sahrosa** [comment]
Aguardando resposta na #49 para priorizar ou não

**Comment by jeankirchner** [comment]
Conforme conversa com o @mformiga e @almeidafab não será considerado como parte do termo de recusa.

**Comment by cv** [comment]
Isso é a #303? Se sim, pode fechar este?

**Comment by sahrosa** [comment]
Concordo que a #303 resolve essa!
