### ISSUE TITLE
Melhorias nas etapas (passo-a-passo)

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#59]
De acordo com o cartão #49:
>VI ­ fornecimento de informações acerca das etapas, presentes e futuras, esperadas para a realização dos serviços, inclusive estimativas de prazos; ** na nossa visão este item seria atendido pelo detalhamento dos passos, inclusive com prazos, custos e resultados dos passos.

**Comment by sahrosa** [comment]
Aguardando resposta na #49 para priorizar ou não

**Comment by cv** [comment]
Já temos etapas, então este cartão perdeu o sentido.
