### ISSUE TITLE
Viabilidade de integração automática do VCGE

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#62]
> 12.2 Temos que ver com Roberto Lyra quando será publicada a nova versão. Precisamos analisar a viabilidade de uma integração automática com o VCGE a fim de não termos custo de atualização das versões

**Comment by sahrosa** [comment]
Para concluir os itens solicitados no termo de recusa, precisamos finalizar essa issue @mformiga @almeidafab? Acreditamos que isso pode ser considerado uma feature nova.

**Comment by mformiga** [comment]
@sahrosa, não precisamos finalizar este issue neste momento. Pode ser uma feature nova.

**Comment by oliviagj** [comment]
praticamente inviável
