### ISSUE TITLE
Seleção e padronização de documentos

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#63]
Para que os tipos de documentos sejam claros, e consistentes (mesmo alias para carteira de identidade, rg, registro geral, por exemplo) iremos estudar uma forma de mapear todos os documentos a partir de tipo de documento (certidões, registros, etc). 

Com isso teremos uma padronização e melhor estrutura de documentos. Esse cartão surgiu como melhoria do #38.

**Comment by jeankirchner** [comment]
Também considerar para na solução para informar os documentos, como serão informados os publicos alvos desses documentos. Conforme #38.

**Comment by oliviagj** [comment]
@mformiga e @almeidafab pensamos que o problema que isso resolve é melhor resolvido com Guia de Estilos e acompanhamento do conteúdo (treinamento, DEDDI/SEGEPE)
