### ISSUE TITLE
Validação de campos ao publicar um serviço

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#71]
Quando um servidor publicar um serviço no Editor, algumas validações deverão ser feitas. 

**Em todos os cenários:**
* As validações deverão limitar o tipo de conteúdo permitido no campo. Exemplo: campo de custo deverá aceitar apenas números.

**Cenário cadastro completo:** 
* Se todos os campos obrigatórios forem preenchidos corretamente, o serviço deverá enviar uma mensagem de feedback positivo, mostrando que o serviço foi publicado e será mostrado no Portal em alguns instantes.

**Cenário cadastro incompleto:** 
* Se um ou mais campos obrigatórios não forem corretamente prenchidos, deveremos apresentar uma mensagem de erro amigável mostrando quais campos ainda devem ser preenchidos para que o serviço possa ser publicado.
* Na mensagem de erro é possível citar o Decreto 6932 para lembrar que as informações completas de cartas de serviço estão previstas em lei.

**Comment by sahrosa** [comment]
#120, #121 e #122 criadas pra quebrar essa validação

**Comment by sahrosa** [comment]
Este cartão foi quebrado nos cartões: #198 #210 #211 #212 #213 #214 #215 #216 #217 #218 #219 #222 #223 #224 #225 #226 #227
