### ISSUE TITLE
Notificar servidores ao publicar novas versões de serviços

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#72]
Sempre que um serviço for publicado (ou republicado), deveremos notificar a publicação através de um e-mail de confirmação que deverá conter as seguintes informações:
* Nome do serviço publicado
* Hora e dia da publicação
* Link para o serviço publicado
* Órgão responsável
* Servidor que publicou o serviço
* Servidor que aprovou a publicação do serviço

**Comment by sahrosa** [comment]
**Dúvida:** Deveremos notificar apenas o servidores envolvidos com o serviço? Ou também envolver os órgãos responsáveis pelo serviço? Alguém mais deverá receber a notificação? 

O que acham @almeidafab e @mformiga?

**Comment by mformiga** [comment]
@sahrosa Notifica todos os perfis atribuídos como publicadores pelo ponto focal do órgão responsável pelo serviço. Os publicadores deixarão de receber as notificações quando:

1. Não pertencer mais ao órgão prestador do serviço (consulta automática pelo webservice do siapenet)
2. Perfil retirado pelo ponto focal

**Comment by sahrosa** [comment]
Pessoal, fechando este cartão pois está fora do escopo, ok @almeidafab @mformiga @gustavo-freitas ?
