### ISSUE TITLE
Fila para publicação de serviços

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/editor-de-servicos#73]
Alterações em serviços, quando válidos, devem estar disponíveis em uma fila de publicação de serviços, para que possam ser publicados.

**Itens na fila devem conter os campos:**
- [ ] Serviço alterado.
- [ ] Há quanto tempo foi criado.
- [ ] Usuário que editou o serviço.

**Ações possíveis:**
- [ ] Edição na fila de publicação deve poder ser aceita e publicada.
- [ ] Edição na fila de publicação deve poder ser recusada.

**Outra situações:**
- [ ] Alterações que entrarem em conflito, devem ser notificadas ao publicador, e serem recusadas automaticamente.
- [ ] Deve ser possível ver as alteração de um serviço que está na fila de publicação.
- [ ] Apenas super usuários, administradores e publicadores devem ter acesso à fila.
- [ ] Deve ser possível executar ações em batch (recusar alterações, publicar alterações).
- [ ] Fila de publicação deve ter filtro de visualização por campos (serviço alterado, usuário que editou o serviço, etc).

**Comment by sahrosa** [comment]
@cv @jeankirchner podemos colocar o item "batch" de ações em um novo cartão? Para deixar este cartão mais simplificado?

**Comment by jeankirchner** [comment]
@sahrosa Acho que cada um dos itens a seguir pode virar um cartão, com exceção dos subitens, +- em ordem de prioridade. O que vc acha? Tenta ver se não esqueci de nada.

- No painel do publicador, ter um link para a página do github, e gerenciar por lá
- Adicionar uma lista de pull requests, apenas com o campo "serviço" que foi editado
- Adicionar campo usuário que editou
- Adicionar campo data de edição (ou esse serviço foi editado a x dias)
- Adicionar ação de aprovar edição - por item
     - Informar se deu algum erro de conflito durante a aprovação, e que deve tratado diretamente no github
- Adicionar ação de recusar edição - por item
- Verificar permissão de acesso à fila de publicação (apenas publicadores podem publicar)
    - Esse item está nesse nível, pois já há algumas funcionalidades básicas para ter controle de usuário, antes desse momento, como algumas coisas podem acontecer pelo github, não faz sentido controle de usuário nosso, sendo que o github vai ter apenas o usuário do editor
- Adicionar ação de ver a diferença de conteúdo no github (meramente um link)
     - Ver diferença de conteúdo de xml vsasdf próprio painel
     -Aqui podemos discutir para que lado queremos evoluir:
         - Mostrar a versão atual do serviço renderizado, vs a versão nova (depois de aprovação de edição)
         - Ou mostrar formulário simples (sem todos os textos) do serviço, mostrando a diferença de cada campo ( um formulário no lado do outro)
- Permitir filtrar edições por órgão
- Permitir filtrar edições por serviço
- Permitir filtrar edições por data
- Permitir filtrar por usuário
- Permitir rejeição de várias edições com uma ação
- Ao aprovar item, informar que um conflito ocorreu, e permitir descartar (ou descartar automáticamente)
- Permitir aprovação de várias edições com uma ação
     - Listar os que deram conflito, ou algum tipo de erro
- Mostrar nos itens da lista de edições pendentes, quais que vão dar conflito

**Comment by sahrosa** [comment]
Gostei da ideia @jeankirchner, mas fiquei pensando se não podemos quebrar em:
* Cartão 1: Fila de publicação mais básica possível
* Cartões 2, 3, 4...: Novas features em cima da lista de publicação básica

O que acha desse modelo? Assim teremos um mínimo necessário e posteriormente vamos adicionando os extras (quem editou, há quanto tempo, etc etc)

**Comment by jeankirchner** [comment]
Legal, foi nessa idéia que eu pensei :)

Imaginei o seguinte: fila de publicação mais básica possível que entrega
algum valor, caso todo o mais dê errado -> link para gerenciar pelo github

Cada um dos cartões seguintes entregam um pouquinho de valor a mais, só
dando a informação, e eventualmente o Github não é mais necessário para
nada (embora ter um link para ele é sempre bom, até para coisas que não
previmos e que ele pode permitir). Isso é bom porque:

- Fica bem simples e claro o que tem que ser feito em cada cartão
- Não ficamos muito tempo em um único cartão, e temos uma percepção melhor
de progresso
- Conseguimos paralelizar o trabalho melhor, identificando dependências
quando quebrado dessa forma
- Nos possibilita repriorizar se for necessário quando pequenas
funcionalidades estiverem sendo feitas. Já se um cartão é muito demorado, é
difícil e mais arriscado parar para fazer outra coisa
- Conseguimos homologar mais fácil dividindo os problemas e soluções, pois
as discussões também ficam bem separadas e focadas naquele ponto específico
- Se um ponto pequenos desses ficar polêmico e entrar em discussão, ele não
começa a bater em vários outros e bloquear outras coisas
- Cada cartão individualmente entrega um pouquinho de valor, embora não
seja todo o valor desejado

Eu tenho uma sensação que parece bem mais fácil de trabalhar assim, e minha
sensação de completude parece bem mais clara.

Claro que cada um dos cartões foram apenas sugestões!

**Comment by sahrosa** [comment]
Essa pode ser a versão mais básica, por exemplo: 

![img_20150630_170807116](https://cloud.githubusercontent.com/assets/2932644/8440836/34940b62-1f4b-11e5-8d56-c03a77a9d014.jpg)

**Comment by sahrosa** [comment]
Cartão #92 criado para a versão mais básica da fila de publicação.
