### ISSUE TITLE
Permissões básicas para publicação de serviços

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#76]
A publicação de serviços deve ser moderada. 

Para realizar um controle inicial, cadastraremos usuários de forma manual. Estes usuários poderão publicar serviços, utilizando a fila de publicação.

**Comment by cv** [comment]
Depende da #77

**Comment by kchnr** [comment]
Esse cartão será tratado nos cartões #324, #331, #332, #333, #334, #335
