### ISSUE TITLE
Controle de usuários de publicação

### ISSUE THREAD

**Issue by kchnr** [servicosgovbr/editor-de-servicos#77]
Vamos ter quatro níveis de usuários:
- Editores: usuários que tem permissão para navegar, editar e salvar alterações.
- Publicadores: tem permissão para publicar serviços e a página do órgão do qual faz parte
- Admin: pode cadastrar novos publicadores dentro do órgão do qual faz parte
- Super admin: pode cadastrar usuários com permissão de Admin, independente de órgão

Possíveis campos:
- CPF
- SIAPE (controle interno do governo)
- Email
- Órgão

**Comment by cv** [comment]
O @mformiga conseguiu bastante informação sobre os webservices do SiapeNet. Vou dar um jeito de disponibilizá-la no repositório. Por enquanto, este [link nos permite testar as chamadas](http://www.soapclient.com/soapclient?template=%2Fclientform.html&fn=soapform&SoapTemplate=%2FSoapResult.html&SoapWSDL=https%3A%2F%2Fwww1.siapenet.gov.br%2FWSSiapenet%2Fservices%2FConsultaSIAPE%3Fwsdl&_ArraySize=2) ao WS.

**Comment by cv** [comment]
Estamos bloqueados enquanto não temos mais informação sobre os parâmetros necessários para chamar o serviço.

**Comment by cv** [comment]
@almeidafab alguma novidade em relação ao GERID?

**Comment by mformiga** [comment]
@cv ainda não temos novidade em relação a isso mas estamos acompanhando.

**Comment by augusto-herrmann** [comment]
Vocês chegaram a considerar a possibilidade de usar o Mozilla [Persona](https://developer.mozilla.org/en-US/Persona)? O portal [Colab](https://colab.interlegis.leg.br/) do Interlegis usa, integrando logins de várias aplicações numa única UI, e funciona muito bem. A principal vantagem dele sobre sistemas semelhantes é a maior foco na privacidade do usuário - o provedor de login não tem como rastrear em quais sites ele está se autenticando.

**Comment by kchnr** [comment]
O @cv quebrou um pouco o que ainda precisa ser feito:

* adicionar um Redis à infra pra ter dados persistentes (precisa mapear o volume pro lugar certo la no docker, etc)
* migrar alguns toggles que podem ser necessarios ligar/desligar em runtime sem reiniciar o stack pro redis tb
* migrar pds-persistente do portal/elasticsearch pro redis
* adicionar uma hash de email -> permissão no redis
* aumentar o objeto UserProfile pra ter esse conjunto de permissões tb
* adicionar todos os emails novos (quando alguem se loga pela primeira vez) nesse hash
* bolar uma telinha pra dar/remover permissões pros usuários
* dar permissão apenas aos admins pra essa tela
* fechar todos os metodos relevantes do RepositorioGit ou ConteudoVersionado às permissões dos usuários (baba de fazer no spring security)
* bolar um endpoint pra verificar as permissoes do usuario (se bobear pode até pegar carona no `/editar/api/ping`, que ja volta o profile mesmo)
* adicionar `if`s na UI pra nao mostrar funcionalidades que o usuario nao tem acesso
* migrar caches do editor pra redis (o RedisCache é bem mais facil de inspecionar que o guava que a gente usa hoje)
* migrar caches do portal pra redis (idem acima)
* corrigir o req.remoteUser nos logs (tá vindo vazio desde que a gente migrou pro OAuth)

**Comment by kchnr** [comment]
Esse cartão será tratado nos cartões #324, #331, #332, #333, #334, #335
