### ISSUE TITLE
Incluir campo no editor para contato do serviço

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/editor-de-servicos#78]
@mformiga Adicionei, pode editar e complementar :)

**Comment by sahrosa** [comment]
@jeankirchner pode descrever melhor este cartão? :)

**Comment by sahrosa** [comment]
Esse cartão ainda faz sentido @jeankirchner?

**Comment by mformiga** [comment]
Oi @sahrosa, este campo será opcional. Deve ser um contato diferente da ouvidoria e sic. Alguns órgãos possuem esta informação, tais como Mec, receita, etc

**Comment by mformiga** [comment]
Os tipos são praticamente os mesmos que temos para os canais de prestação.

**Comment by cv** [comment]
Esse não é um campo referente ao órgão, e não ao serviço?

**Comment by jeankirchner** [comment]
@mformiga, poderia descrever melhor a finalidade desse campo? Como será usado pelo cidadão, por exemplo? Isso nos ajudaria a clarificar o que/como vamos fazer.

**Comment by mformiga** [comment]
@jeankirchner e @cv este é um atributo do órgão
