### ISSUE TITLE
Incluir área de ações

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#86]
Conforme comentamos no cartão https://github.com/servicosgovbr/portal-de-servicos/issues/398 vamos incluir uma área para incluir os links de ações possíveis através de um serviço. Até agora temos os seguintes campos.

* Agendar um atendimento
* Inscrever no programa
* Simular financiamento
* Calcular taxas
* Acompanhar

**Comment by cv** [comment]
Acho que estas ações estão muito "viciadas" ao que faria sentido para o Fies, @sahrosa - mas muitos serviços têm verbos nos nomes, o que ajuda:

* [Consultar](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico/consulta-situacao-do-requerimento-de-beneficio-previdenciario)
* [Emitir](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico/emissao-de-certidao-previdenciaria-certidao-contribuicoes-previdenciarias-certidoes-e-situacao-fiscal)
* [Preencher](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico/dasn-simei-declaracao-anual-para-o-microempreendedor-individual)
* [Declarar](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico/declaracao-simplificada-de-pj-inativa)

…e por aí vai.

**Comment by sahrosa** [comment]
Sim! 

O problema é que usando só o título da ação, algumas pessoas com quem testei não entendiam o que elas iriam simular/inscrever/etc. E aí incluímos uma contextualização maior.

Claro que testando e editando manualmente ficou super fácil. Agora é pensar em uma forma mais automática de fazer isso... 
* Talvez colocando muitas opções (simular, simular financiamento, emitir, emitir fatura, e por aí em diante),
* Ou combinando ação com um texto... botão simular + [digite texto complementar] (**pode dar muito errado essa aqui**)
* Outras opções, que vou pesquisando aqui e podem surgir como ideias do pessoal.

**Comment by sahrosa** [comment]
Simplificamos este cartão através do cartão #88. Dessa forma resolveremos a necessidade básica. No futuro poderemos adicionar maiores complexidades, se necessárias.
