### ISSUE TITLE
Áreas de interesse no menu esquerdo

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/editor-de-servicos#89]
Acreditamos que possibilitar navegação por áreas de interesse poderá auxiliar usuários a encontrarem serviços mais facilmente (pois as áreas de interesse estão melhor organizadas que as linhas da vida, que hoje estão no menu esquerdo). 

Para isso poderemos adicionar uma seção de áreas de interesse com as áreas de interesse utilizadas pelos serviços na página inicial do Portal.

Saberemos que obtivemos sucesso quando o uso dos itens de área de interesse for igual ou maior do que o uso do itens da seção "Categorias"

**Comment by sahrosa** [comment]
Tenho dúvidas sobre esta hipótese, pois apesar de sabermos que áreas de interesse e linhas da vida serem diferente, elas são *muito* semelhantes, e podem ao invés de facilitar a vida do cidadão, atrapalhar ainda mais.

Que tal mostrar para 50% dos usuários as categorias de linhas da vida, e mostrar para os outros 50% as categorias de áreas de interesse. Posteriormente comparar os dados e decidir quais das duas categorizações deverão ser usadas. O que acham @cv @jeankirchner?

Outra possibilidade é trocarmos as categorias de linha da vida pelas áreas de interesse – já que essas estão melhor estruturadas. E então deixamos por um período de 15 dias (por exemplo), e posteriormente comparamos com os dados de uso das categorias de linhas da vida?

Acredito realmente que deixar as duas pode ser muito confuso para os cidadãos.

**Comment by cv** [comment]
Concordo, deixar as duas navegações ligadas vai confundir bastante.

O teste 50/50 ainda não é tecnicamente possível (a gente não tem como dizer
pro piwik se o usuário veio da população A ou B sem perder as campanhas que
já existem), e pode ser bem complicado de analisar.
​
Proponho então que a gente desabilite as linhas da vida por um tempo (ou de
vez, caso as áreas de interesse sejam melhores). Que tall, @mformiga e
@almeidafab?

**Comment by almeidafab** [comment]
@cv acho que a linha da vida e área de interesse são importantes e concordo que mostrar as duas no menu vai confundir o usuário. Vale lembrar que nem todo serviço possui uma linha da vida, mas todos possuem uma area de interesse. Até pensei em utilizar a area de interesse como uma forma de refinar a pesquisa em uma opção de "busca avançada" e deixaria a linha da vida no menu esquerdo. Isso precisa de mais discussão e vamos levar essa pauta na reunião de quinta com asege e segep. Atualizo vocês posteriormente.

**Comment by sahrosa** [comment]
Show! Obrigada @almeidafab. Aguardamos :)

**Comment by almeidafab** [comment]
@sahrosa acabamos de nos reunir com a asege e segep e eles também gostaram da ideia de utilizar a área de interesse em uma busca avançada. Precisamos discutir depois em que momento essa funcionalidade entraria e definir os critérios que farão parte da busca.

**Comment by almeidafab** [comment]
@sahrosa @cv estamos com muitas dúvidas com relação a area de interesse. O @mformiga sugeriu colocar no menu esquerdo, dentro de "Listas" uma opção "Assuntos" que ao clicar abre uma página com a lista do vcge. Ao mesmo tempo o menu de linhas da vida é minimizado. 
Não temos certeza se colocar o vcge em uma busca avançada seria uma boa opção. 
O que vcs acham? Propostas?

**Comment by sahrosa** [comment]
Oi @almeidafab e @mformiga! 

Eu acho que a primeira questão que queremos responder é qual das duas categorizações que queremos usar como preferencial. Apesar das duas serem conceitualmente muito diferentes, acabam se parecendo. Olhando hoje, me parece que as áreas de interesse são mais ricas que a linha da vida. Mas isso é uma opinião pessoal, e seria importante validar através de algum tipo de teste.

Uma ideia legal que surgiu conversando com @jeankirchner era talvez termos as áreas mais explícitas na página inicial, como na Australia ou Noruega ou até Reino Unido (abaixo). O que acham de testarmos algo nessa linha?

![image](https://cloud.githubusercontent.com/assets/2932644/8527877/90e32526-23e5-11e5-8e18-1af9e2ea4caa.png)

![image](https://cloud.githubusercontent.com/assets/2932644/8527826/368b6c78-23e5-11e5-915d-f12b4ed9323e.png)

![screen shot 2015-07-06 at 1 50 35 pm](https://cloud.githubusercontent.com/assets/2932644/8527941/088ef0dc-23e6-11e5-8dd2-f74749d00e56.png)

**Comment by almeidafab** [comment]
@sahrosa podemos fazer um teste sim. Pode fazer um esboço até para vermos como ficaria.

**Comment by sahrosa** [comment]
Legal @almeidafab! Vou pegar isso assim que possível :)

**Comment by oliviagj** [comment]
duplicou na #182
