### ISSUE TITLE
Fila de publicação: mostrar há quanto tempo o serviço foi editado

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#93]
Acreditamos que mostrar há quanto tempo um serviço foi editado na fila de publicação será útil para o servidor que tomará a decisão de aprovar ou recusar a edição de um serviço.

Regra do tempo de edição (regra parecida com a do Github):
* Serviço editado há 1 minuto
* Serviço editado há 59 minutos
* Serviço editado há 1 hora
* Serviço editado há 23 horas
* Serviço editado há 1 dia
* Serviço editado há 29 dias
* Serviço editado há 1 mês
* Serviço editado há 11 meses
* Serviço editado há mais de 1 ano

![img_20150630_173756805](https://cloud.githubusercontent.com/assets/2932644/8441483/ec7905b8-1f4e-11e5-9eab-53e5727eac24.jpg)

**Comment by cv** [comment]
Resolvido pelo #274
