### ISSUE TITLE
Fila de publicação: nome do usuário que editou o serviço

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#94]
Acreditamos que mostrar quem editou um serviço na fila de publicação será útil para o servidor que tomará a decisão de aprovar ou recusar a edição de um serviço.

![img_20150630_182330730](https://cloud.githubusercontent.com/assets/2932644/8442419/5995f222-1f55-11e5-81ab-2824c25c5498.jpg)

**Comment by cv** [comment]
Resolvido pelo #274
