### ISSUE TITLE
Fila de publicação: mostrar alterações realizadas no pull request

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#95]
Acreditamos que devemos mostrar quais alterações foram realizadas durante uma submissão de edição de serviço.

**Este cartão deve ser complementado.** 

Algumas possibilidades são:
* Adicionar ação de ver a diferença de conteúdo no github (meramente um link)
* Ver diferença de conteúdo de xml na própria fila de publicação.
* Mostrar a versão atual do serviço x versão nova (depois de aprovação de edição)
* Mostrar formulário simples (sem todos os textos) do serviço, mostrando a diferença de cada campo (um formulário no lado do outro)

**Comment by cv** [comment]
Podemos mostrar o botão Visualizar na fila de publicação, que depende da #75.
