### ISSUE TITLE
Fila de publicação: filtro por nome do serviço editado

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/editor-de-servicos#97]
Acreditamos que dar a opção dos servidores filtrarem as edições de serviços por nome do serviço editado será útil para que o servidor possa aprovar ou recusar edições de serviços de forma mais ágil.

**Comment by oliviagj** [comment]
resolvido pela #274

**Comment by oliviagj** [comment]
resolvido pela #274 

não temos a aprovação ainda, mas a tela já tem esse filtro. quando tivermos login um pouco dessa lógica muda, mas cada coisa a seu tempo
